import { Role } from '../../common/interfaces/role.enum';
import { AiAssistantType } from '../../chatbot/schemas/ai-assistant-profile.schema';
import { AiSituationDefinition } from '../ai-core.types';

const DIRECTOR = AiAssistantType.DIRECTOR_OPERATIONS;
const ACCOUNTING = AiAssistantType.ACCOUNTING_OPERATIONS;
const OPS = AiAssistantType.OPS_OPERATIONS;
const TEACHER = AiAssistantType.TEACHER_SUPPORT;
const EXPERIENCE_TEACHER = AiAssistantType.EXPERIENCE_TEACHER_SUPPORT;
const PARENT = AiAssistantType.PARENT_SUPPORT;
const STUDENT = AiAssistantType.STUDENT_SUPPORT;
const SALE = AiAssistantType.SALE_OPERATIONS;
const ADS = AiAssistantType.ADS_OPERATIONS;
const SHAREHOLDER = AiAssistantType.SHAREHOLDER_INSIGHTS;
const INTERNAL = AiAssistantType.INTERNAL_SUPPORT;
const LEAD_CARE = AiAssistantType.LEAD_CARE;

export const AI_CORE_SITUATION_CATALOG: readonly AiSituationDefinition[] = [
  {
    key: 'system_guide',
    capability: 'SYSTEM_GUIDE',
    userIntent: 'Hoi cach dung he thong, vao man hinh nao, quy trinh thao tac.',
    examples: ['Muon xem cong no thi vao dau?', 'Quy trinh dau ngay la gi?'],
    triggerKeywords: ['huong dan', 'cach dung', 'vao dau', 'man hinh', 'quy trinh', 'sop', 'su dung he thong'],
    allowedAssistantTypes: [DIRECTOR, ACCOUNTING, OPS, TEACHER, EXPERIENCE_TEACHER, PARENT, STUDENT, SALE, ADS, SHAREHOLDER, INTERNAL, LEAD_CARE],
    allowedRoles: [Role.DIRECTOR, Role.ACCOUNTING, Role.OPS, Role.TEACHER, Role.EXPERIENCE_TEACHER, Role.PARENT, Role.STUDENT, Role.SALE, Role.ADSMANAGER, Role.SHAREHOLDER],
    operation: 'READ_SUMMARY',
    dataScope: 'NO_DATABASE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: [
      'system_guide',
      'accounting_guide',
      'ops_guide',
      'teacher_guide',
      'sale_guide',
      'parent_guide',
      'student_guide',
      'ads_guide',
      'shareholder_guide',
    ],
    requiredEntities: [],
    contextPolicy: 'Chi doc static guide, khong doc database neu user chi hoi cach dung.',
    missingDataPolicy: 'Neu guide thieu, de xuat man hinh/cap nhat guide.',
    writePolicy: 'Khong ghi.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: false,
  },
  {
    key: 'daily_work_queue',
    capability: 'DAILY_WORK',
    userIntent: 'Hoi hom nay can lam gi, viec nao qua han, uu tien nao can xu ly.',
    examples: ['Hom nay toi can xu ly gi?', 'Viec nao dang qua han?'],
    triggerKeywords: ['hom nay', 'viec trong ngay', 'can lam gi', 'can xu ly', 'uu tien', 'qua han', 'deadline'],
    allowedAssistantTypes: [DIRECTOR, ACCOUNTING, OPS, TEACHER, EXPERIENCE_TEACHER, PARENT, SALE, ADS, INTERNAL],
    allowedRoles: [Role.DIRECTOR, Role.ACCOUNTING, Role.OPS, Role.TEACHER, Role.EXPERIENCE_TEACHER, Role.PARENT, Role.SALE, Role.ADSMANAGER],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['daily_tasks'],
    requiredEntities: [],
    contextPolicy: 'Luon lay queue da service gioi han theo role/user.',
    missingDataPolicy: 'Neu khong co task, tra loi khong co viec can xu ly trong context da nap.',
    writePolicy: 'Chi de xuat hanh dong tiep theo.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'experience_teacher_daily_review_packet',
    capability: 'LEARNING_CONTENT',
    userIntent: 'Giao vien review hoi hom nay can cham/review gi: bai tap, quiz tu luan, hoc lieu/rubric lien quan va buoc uu tien.',
    examples: ['Hom nay toi can cham gi?', 'Viec review trong ngay cua toi?', 'Bai tap/quiz nao can uu tien?'],
    triggerKeywords: ['hom nay', 'can lam gi', 'hom nay toi can cham', 'viec review trong ngay', 'can cham gi', 'bai tap quiz can uu tien', 'daily review packet'],
    allowedAssistantTypes: [EXPERIENCE_TEACHER],
    allowedRoles: [Role.EXPERIENCE_TEACHER],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['daily_tasks', 'homework_grading_queue', 'quiz_grading_queue', 'teaching_materials_search', 'teacher_guide'],
    requiredEntities: [],
    contextPolicy: 'Lay queue/summary gioi han: daily tasks, bai tap, quiz va metadata hoc lieu; khong nap file lon.',
    missingDataPolicy: 'Neu queue trong, noi ro khong co bai/quiz pending trong context da nap va goi y mo filter all neu can.',
    writePolicy: 'AI chi phan tich/soan nhan xet; cham diem homework/quiz can action draft va xac nhan.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'executive_overview',
    capability: 'EXECUTIVE_OVERVIEW',
    userIntent: 'Tong quan doanh nghiep, rui ro cap dieu hanh va diem can can thiep.',
    examples: ['Tinh hinh he thong the nao?', 'Diem nao nguy hiem nhat?'],
    triggerKeywords: ['tong quan', 'tinh hinh', 'he thong', 'doanh nghiep', 'suc khoe', 'nguy hiem', 'rui ro tong the'],
    allowedAssistantTypes: [DIRECTOR],
    allowedRoles: [Role.DIRECTOR],
    operation: 'READ_SUMMARY',
    dataScope: 'GLOBAL',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['daily_tasks', 'director_dashboard', 'pending_approvals_summary', 'financial_alerts', 'audit_stats'],
    requiredEntities: [],
    contextPolicy: 'Mac dinh current month; chi aggregate/recent list da gioi han.',
    missingDataPolicy: 'Neu thieu chi tiet, de xuat drill-down theo finance/sales/ops/ticket.',
    writePolicy: 'Chi de xuat.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'director_daily_control_packet',
    capability: 'EXECUTIVE_OVERVIEW',
    userIntent: 'Giam doc hoi brief dieu hanh dau ngay/cuoi ngay, top rui ro va cac quyet dinh lap lai can uu tien.',
    examples: ['Cho toi brief dieu hanh dau ngay', 'Top 5 rui ro can xu ly truoc la gi?', 'Cuoi ngay can check nhung gi?'],
    triggerKeywords: ['brief dieu hanh', 'brief dau ngay', 'brief cuoi ngay', 'top 5 rui ro', 'ban dieu hanh', 'goi quan tri', 'goi dieu hanh', 'uu tien dieu hanh'],
    allowedAssistantTypes: [DIRECTOR],
    allowedRoles: [Role.DIRECTOR],
    operation: 'READ_SUMMARY',
    dataScope: 'GLOBAL',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['daily_tasks', 'director_dashboard', 'pending_approvals_summary', 'financial_alerts', 'audit_stats'],
    requiredEntities: [],
    contextPolicy: 'Mot packet lap lai cho giam doc: chi aggregate, queue count, risk va activity stats; khong nap raw list dai.',
    missingDataPolicy: 'Neu can ra quyet dinh cho mot record cu the, de xuat drill-down entity/detail va khong tu ket luan khi thieu bang chung.',
    writePolicy: 'Chi de xuat thu tu xu ly; moi phe duyet/tu choi/chuyen tien/gui thong bao can draft va confirm rieng.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'director_approval_audit_control',
    capability: 'ADMIN_SECURITY',
    userIntent: 'Giam doc hoi hang cho duyet, audit bat thuong va viec can can thiep truoc khi ra quyet dinh.',
    examples: ['Con gi cho toi duyet?', 'Audit he thong co bat thuong?', 'Viec nao can toi can thiep ngay?'],
    triggerKeywords: ['cho duyet', 'phe duyet', 'audit', 'bat thuong', 'can can thiep', 'canh bao he thong', 'quyet dinh'],
    allowedAssistantTypes: [DIRECTOR],
    allowedRoles: [Role.DIRECTOR],
    operation: 'READ_SUMMARY',
    dataScope: 'GLOBAL',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['daily_tasks', 'pending_approvals_summary', 'audit_stats', 'system_guide'],
    requiredEntities: [],
    contextPolicy: 'Chi nap queue/count va audit stats; detail record can drill-down theo entity/filter.',
    missingDataPolicy: 'Neu thieu chi tiet ban ghi, de xuat mo pending approvals hoac them detail tool phu hop.',
    writePolicy: 'Approve/reject/lock/user action deu can preview, confirm va audit.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'director_approval_risk_triage',
    capability: 'ADMIN_SECURITY',
    userIntent: 'Giam doc muon sap xep hang cho duyet theo rui ro tien, SLA, audit va tac dong van hanh truoc khi quyet dinh.',
    examples: ['Sap xep cac viec cho duyet theo rui ro', 'Viec cho duyet nao nen xu ly truoc?', 'Khoan nao can kiem tra them truoc khi duyet?'],
    triggerKeywords: ['sap xep hang cho duyet', 'rui ro phe duyet', 'duyet truoc', 'tu choi de xuat', 'approval risk', 'hang cho duyet rui ro', 'kiem tra truoc khi duyet'],
    allowedAssistantTypes: [DIRECTOR],
    allowedRoles: [Role.DIRECTOR],
    operation: 'READ_SUMMARY',
    dataScope: 'GLOBAL',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['pending_approvals_summary', 'financial_alerts', 'accounting_dashboard', 'audit_stats', 'system_guide'],
    requiredEntities: [],
    contextPolicy: 'Chi lay summary/alert/stats; uu tien nhom theo tien, deadline, audit bat thuong va loai approval.',
    missingDataPolicy: 'Neu summary khong co record-level reason, noi ro can detail tool theo invoice/payroll/topup/class/ticket truoc khi ket luan.',
    writePolicy: 'AI khong duyet/tu choi truc tiep; chi tao draft hanh dong khi co entity, diff, ly do va nguoi dung xac nhan.',
    riskLevel: 'HIGH',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'director_admin_security_governance',
    capability: 'ADMIN_SECURITY',
    userIntent: 'Giam doc hoi quan tri he thong, phan quyen, audit, AI token/profile/prompt va diem rui ro bao mat.',
    examples: ['Quan tri AI/token co rui ro gi?', 'Audit co thao tac bat thuong khong?', 'Can kiem tra phan quyen nao?'],
    triggerKeywords: ['quan tri ai', 'token ai', 'openai token', 'assistant profile', 'prompt chatbot', 'phan quyen', 'bao mat he thong', 'audit trail', 'nhat ky he thong'],
    allowedAssistantTypes: [DIRECTOR],
    allowedRoles: [Role.DIRECTOR],
    operation: 'READ_SUMMARY',
    dataScope: 'GLOBAL',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['audit_stats', 'daily_tasks', 'pending_approvals_summary', 'system_guide'],
    requiredEntities: [],
    contextPolicy: 'Khong nap secret/token/prompt raw vao AI; chi dung stats, guide va queue da duoc redact.',
    missingDataPolicy: 'Neu user can xem/sua token/profile, de xuat mo man hinh quan tri va khong dua secret vao prompt.',
    writePolicy: 'Cau hinh token, prompt, role/user la critical action: phai co preview, confirm, audit va khong hien secret.',
    riskLevel: 'CRITICAL',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'director_growth_retention_forecast',
    capability: 'EXECUTIVE_OVERVIEW',
    userIntent: 'Giam doc hoi tang truong, retention, churn, du bao doanh thu va diem nghen kinh doanh.',
    examples: ['Retention co xau khong?', 'Du bao doanh thu thang nay?', 'Sales va duy tri hoc vien co diem nghen nao?'],
    triggerKeywords: ['retention', 'duy tri', 'churn', 'du bao', 'forecast', 'tang truong', 'roi bo', 'hoc vien roi'],
    allowedAssistantTypes: [DIRECTOR],
    allowedRoles: [Role.DIRECTOR],
    operation: 'READ_SUMMARY',
    dataScope: 'GLOBAL',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['retention', 'forecast', 'sales_dashboard', 'director_dashboard'],
    requiredEntities: [],
    contextPolicy: 'Dung aggregate, mac dinh current month; khong ket luan nguyen nhan neu context chua co bang chung.',
    missingDataPolicy: 'Neu can nguyen nhan, de xuat drill-down sales/ops/student/class theo filter.',
    writePolicy: 'Khong ghi; chi de xuat viec can lam tiep.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'finance_risk',
    capability: 'FINANCE_CONTROL',
    userIntent: 'Hoi tinh hinh tai chinh, P&L, dong tien, cong no va canh bao.',
    examples: ['Tai chinh thang nay co on khong?', 'Dong tien va cong no the nao?'],
    triggerKeywords: ['tai chinh', 'dong tien', 'cash flow', 'cashflow', 'p&l', 'lai lo', 'loi nhuan', 'chi phi', 'cong no', 'aging', 'canh bao tai chinh'],
    allowedAssistantTypes: [DIRECTOR, ACCOUNTING, SHAREHOLDER],
    allowedRoles: [Role.DIRECTOR, Role.ACCOUNTING, Role.SHAREHOLDER],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['financial_overview', 'financial_alerts', 'profit_and_loss', 'cash_flow', 'aging_report'],
    requiredEntities: [],
    contextPolicy: 'Dung aggregate theo ngay; shareholder chi aggregate khong PII.',
    missingDataPolicy: 'Neu can chi tiet tung invoice/ledger thi de xuat drill-down co filter.',
    writePolicy: 'Khong ghi tien trong buoc doc.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'accounting_queue',
    capability: 'INVOICE_WALLET',
    userIntent: 'Hoi hoa don, vi, top-up, payroll va queue tai chinh can xu ly.',
    examples: ['Hoa don nao cho duyet?', 'Top-up nao dang ton?'],
    triggerKeywords: ['hoa don', 'invoice', 'vi', 'wallet', 'top up', 'topup', 'ledger', 'nap tien', 'payroll', 'luong'],
    allowedAssistantTypes: [DIRECTOR, ACCOUNTING],
    allowedRoles: [Role.DIRECTOR, Role.ACCOUNTING],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['daily_tasks', 'accounting_dashboard', 'accounting_pending_invoices', 'accounting_pending_topups', 'accounting_payroll_summary'],
    requiredEntities: [],
    contextPolicy: 'Director/Accounting dung aggregate/limited list; parent va OPS dung situation rieng theo scope cua minh.',
    missingDataPolicy: 'Neu user can duyet/sua, chuyen sang write preview sau khi co entity id.',
    writePolicy: 'Khong approve/reject trong buoc doc.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'accounting_invoice_wallet_reconciliation',
    capability: 'INVOICE_WALLET',
    userIntent: 'Ke toan hoi hoa don, top-up, vi, chung tu va ticket tai chinh can doi soat.',
    examples: ['Hoa don nao cho duyet?', 'Top-up nao dang ton?', 'Ticket tai chinh nao can bo sung chung tu?'],
    triggerKeywords: ['hoa don cho duyet', 'top-up', 'topup', 'vi', 'wallet', 'chung tu', 'doi soat', 'ticket tai chinh', 'payment proof'],
    allowedAssistantTypes: [ACCOUNTING],
    allowedRoles: [Role.ACCOUNTING],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['accounting_pending_invoices', 'accounting_pending_topups', 'accounting_wallets', 'accounting_ledger', 'accounting_my_tickets'],
    requiredEntities: [],
    contextPolicy: 'Nap queue invoice/top-up/vi/ledger truoc; danh sach phai limit va khong nap anh chung tu lon.',
    missingDataPolicy: 'Neu can invoice cu the, de xuat invoice_detail theo entity resolver.',
    writePolicy: 'Duyet/tu choi/xac nhan tien/ghi chu ticket can preview va confirm.',
    riskLevel: 'HIGH',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'accounting_cashflow_payroll_control',
    capability: 'FINANCE_CONTROL',
    userIntent: 'Ke toan hoi cashflow, P&L, cong no, payroll va canh bao tai chinh can xu ly.',
    examples: ['Dong tien tuan nay co rui ro khong?', 'Cong no qua han?', 'Payroll nao can kiem tra?'],
    triggerKeywords: ['cashflow', 'dong tien', 'p&l', 'cong no', 'aging', 'payroll', 'luong', 'canh bao tai chinh', 'reconciliation'],
    allowedAssistantTypes: [ACCOUNTING],
    allowedRoles: [Role.ACCOUNTING],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['financial_alerts', 'cash_flow', 'profit_and_loss', 'accounting_payroll_summary', 'accounting_staff_payroll_summary'],
    requiredEntities: [],
    contextPolicy: 'Chi aggregate/limited list; group cashflow theo week va khong nap file/export lon.',
    missingDataPolicy: 'Neu can chi tiet tung item/transaction payroll, noi ro can mo detail tool rieng thay vi suy dien.',
    writePolicy: 'Khong ghi giao dich, khong dieu chinh payroll/vi neu chua preview va confirm.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'accounting_collections_aging_packet',
    capability: 'FINANCE_CONTROL',
    userIntent: 'Ke toan hoi cong no, hoa don tre, viec thu tien va ticket/chung tu can bo sung theo chu ky lap lai.',
    examples: ['Cong no nao can thu truoc?', 'Hoa don nao tre han va can goi phu huynh?', 'Ticket tai chinh nao can xu ly de thu tien?'],
    triggerKeywords: ['thu tien', 'cong no qua han', 'hoa don tre', 'aging thu tien', 'can goi phu huynh', 'chung tu thieu', 'collection'],
    allowedAssistantTypes: [ACCOUNTING],
    allowedRoles: [Role.ACCOUNTING],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['aging_report', 'accounting_invoices', 'accounting_ledger', 'accounting_pending_topups', 'accounting_my_tickets'],
    requiredEntities: [],
    contextPolicy: 'Dung aging/alert truoc, chi nap danh sach hoa don/ticket da limit; khong nap anh chung tu hay ledger raw.',
    missingDataPolicy: 'Neu can thu/nhac mot hoa don cu the, can invoice_detail va draft message/action rieng.',
    writePolicy: 'Khong xac nhan tien/doi invoice/nhac no tu dong; moi message/payment action can preview va confirm.',
    riskLevel: 'HIGH',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'accounting_month_end_close_packet',
    capability: 'FINANCE_CONTROL',
    userIntent: 'Ke toan hoi chot so cuoi thang, P&L, cashflow, cong no va cac sai lech can doi soat.',
    examples: ['Cuoi thang can chot nhung muc nao?', 'P&L va cashflow co sai lech nao?', 'Checklist dong so thang nay'],
    triggerKeywords: ['chot so', 'cuoi thang', 'month end', 'dong so', 'doi soat cuoi thang', 'sai lech tai chinh', 'closing'],
    allowedAssistantTypes: [ACCOUNTING],
    allowedRoles: [Role.ACCOUNTING],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['profit_and_loss', 'cash_flow', 'accounting_expense_stats', 'accounting_bank_reconciliation', 'accounting_loan_summary'],
    requiredEntities: [],
    contextPolicy: 'Chi dung aggregate theo ky; group cashflow theo week va neu ro source route cua so lieu.',
    missingDataPolicy: 'Neu thieu bankAccountId cho reconciliation hoac tax detail, noi ro du lieu can bo sung thay vi tu suy dien.',
    writePolicy: 'Khong khoa so/xuat bao cao chinh thuc khi chua co workflow export/approval.',
    riskLevel: 'HIGH',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'accounting_payroll_payout_packet',
    capability: 'PAYROLL_COMPENSATION',
    userIntent: 'Ke toan hoi chu ky luong, pending payout, dong tien tra luong va tranh chap luong can xu ly.',
    examples: ['Payroll nao can kiem tra truoc khi tra?', 'Dong tien tra luong co du khong?', 'Ticket tranh chap luong nao dang mo?'],
    triggerKeywords: ['chu ky luong', 'payroll cycle', 'pending payout', 'tra luong', 'tranh chap luong', 'giu luong', 'bang luong can kiem tra'],
    allowedAssistantTypes: [ACCOUNTING],
    allowedRoles: [Role.ACCOUNTING],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['accounting_payroll_summary', 'accounting_payrolls', 'accounting_staff_payroll_summary', 'accounting_staff_payrolls', 'cash_flow'],
    requiredEntities: [],
    contextPolicy: 'Dung summary/list payroll/cashflow da limit; khong nap chi tiet item bang luong neu chua co payroll detail tool.',
    missingDataPolicy: 'Neu can item/transaction cu the trong bang luong, noi ro can payroll detail tool truoc khi de xuat thanh toan.',
    writePolicy: 'Generate/submit/mark-paid/hold-release payroll la high-risk action can preview, confirm va audit.',
    riskLevel: 'HIGH',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'accounting_bank_fund_expense_control',
    capability: 'FINANCE_CONTROL',
    userIntent: 'Ke toan hoi ngan hang, quy, giao dich ngan hang/quy, chi phi va OPEX can doi soat.',
    examples: ['So du ngan hang va quy hien tai?', 'Giao dich ngan hang nao can doi soat?', 'Chi phi thang nay theo danh muc?'],
    triggerKeywords: ['ngan hang', 'bank', 'tai khoan ngan hang', 'bank transaction', 'giao dich ngan hang', 'quy', 'fund', 'giao dich quy', 'chi phi', 'expense', 'opex', 'mua sam'],
    allowedAssistantTypes: [ACCOUNTING],
    allowedRoles: [Role.ACCOUNTING],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['accounting_bank_accounts_summary', 'accounting_bank_transactions', 'accounting_funds_summary', 'accounting_fund_transactions', 'accounting_expense_stats'],
    requiredEntities: [],
    contextPolicy: 'Dung summary ngan hang/quy va list transaction/expense da limit; khong nap file/chung tu dinh kem.',
    missingDataPolicy: 'Neu can reconciliation chi tiet, can filter bankAccountId hoac chuyen sang situation doi soat cuoi ky.',
    writePolicy: 'Record/reconcile transaction, dieu chinh quy hoac thanh toan expense can preview, confirm va audit.',
    riskLevel: 'HIGH',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'accounting_loan_debt_control',
    capability: 'FINANCE_CONTROL',
    userIntent: 'Ke toan hoi khoan vay, nghia vu tra vay, lich den han va tac dong dong tien.',
    examples: ['Khoan vay nao den han thang nay?', 'Tong no vay hien tai?', 'Lich tra vay qua han?'],
    triggerKeywords: ['khoan vay', 'loan', 'vay', 'no vay', 'lich tra vay', 'tra vay', 'lender', 'qua han vay', 'den han vay'],
    allowedAssistantTypes: [ACCOUNTING],
    allowedRoles: [Role.ACCOUNTING],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['accounting_loan_summary', 'accounting_loans', 'accounting_loan_payments_due', 'cash_flow', 'financial_alerts'],
    requiredEntities: [],
    contextPolicy: 'Dung summary/list loan va lich den han da limit; ket hop cashflow de nhan dien rui ro thanh toan.',
    missingDataPolicy: 'Neu can chi tiet mot khoan vay, can entity/filter loanId truoc khi soan buoc thanh toan.',
    writePolicy: 'Activate loan/record payment/restructure loan can preview, confirm va audit.',
    riskLevel: 'HIGH',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'sales_pipeline',
    capability: 'SALES_CRM',
    userIntent: 'Hoi lead, order, pipeline, chuyen doi va diem nghen sales.',
    examples: ['Pipeline thang nay ra sao?', 'Lead nao can cham soc?'],
    triggerKeywords: ['sales', 'sale', 'lead', 'order', 'pipeline', 'chuyen doi', 'conversion', 'don hang', 'follow up'],
    allowedAssistantTypes: [DIRECTOR, OPS, SALE, LEAD_CARE],
    allowedRoles: [Role.DIRECTOR, Role.OPS, Role.SALE],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['sale_next_best_actions', 'sales_dashboard', 'sale_lead_pipeline', 'sale_followups_due', 'sale_order_pipeline'],
    requiredEntities: [],
    contextPolicy: 'SALE chi scope cua sale dang dang nhap.',
    missingDataPolicy: 'Neu can tung lead/order, yeu cau drill-down voi filter/entity.',
    writePolicy: 'Khong tao/sua lead/order trong buoc doc.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'sale_next_best_actions_packet',
    capability: 'SALES_CRM',
    userIntent: 'Sale hoi viec uu tien can lam tiep theo, diem nghen pipeline, lead/order/trial/conversation nao nen xu ly truoc de chot doanh thu.',
    examples: ['Hom nay toi can lam gi de chot doanh thu?', 'Pipeline cua toi dang nghen o dau?', 'Lead/order/trial nao nen xu ly truoc?', 'Next best action cua toi la gi?'],
    triggerKeywords: ['next best action', 'viec sale uu tien', 'uu tien sale', 'hom nay toi can lam gi', 'can lam gi de chot', 'xu ly truoc', 'nen lam gi truoc', 'pipeline cua toi dang nghen', 'nghen o dau', 'can chot truoc', 'chot doanh thu'],
    allowedAssistantTypes: [SALE],
    allowedRoles: [Role.SALE],
    operation: 'READ_SUMMARY',
    dataScope: 'ASSIGNED_RECORDS',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['sale_next_best_actions', 'sale_conversations', 'sale_followups_due', 'sale_trial_summary', 'sale_commission_report'],
    requiredEntities: [],
    contextPolicy: 'Dung packet scoring da gom lead, stale, order, trial, conversation va commission; AI phai dua rank/evidence truoc, khong tu them action ngoai context.',
    missingDataPolicy: 'Neu packet rong, noi ro khong co viec uu tien cao va de xuat mo leads/orders/trials/conversations de loc rong hon.',
    writePolicy: 'AI chi de xuat va soan draft; cap nhat lead/order/trial/gui tin nhan can preview va xac nhan.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'sale_daily_followups',
    capability: 'SALES_CRM',
    userIntent: 'Sale hoi lead den han follow-up, viec cham soc trong ngay va uu tien lien he.',
    examples: ['Lead nao can follow-up hom nay?', 'Danh sach phu huynh can cham soc', 'Viec sale can xu ly trong ngay?'],
    triggerKeywords: ['follow up', 'follow-up', 'can cham soc', 'cham soc lead', 'lead den han', 'lead can goi', 'goi lai', 'lien he lai', 'viec sale'],
    allowedAssistantTypes: [SALE, LEAD_CARE],
    allowedRoles: [Role.SALE],
    operation: 'READ_DETAIL',
    dataScope: 'ASSIGNED_RECORDS',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['daily_tasks', 'sale_followups_due', 'sale_lead_pipeline', 'sales_dashboard'],
    requiredEntities: [],
    contextPolicy: 'Chi nap lead den han trong scope sale dang dang nhap; uu tien nextFollowUp gan nhat.',
    missingDataPolicy: 'Neu queue rong, noi ro khong co lead den han va goi y xem pipeline/stale lead.',
    writePolicy: 'AI chi soan noi dung cham soc; cap nhat contact/follow-up/status can preview va xac nhan.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'sale_lead_pipeline_review',
    capability: 'SALES_CRM',
    userIntent: 'Sale hoi pipeline lead cua minh, ty le chuyen doi, lead theo trang thai va diem nghen cham soc.',
    examples: ['Pipeline lead cua toi the nao?', 'Lead nao dang consulting?', 'Ty le chuyen doi cua toi?'],
    triggerKeywords: ['pipeline lead', 'lead cua toi', 'ty le chuyen doi', 'conversion cua toi', 'lead moi', 'consulting', 'interested', 'stale lead', 'lead qua han'],
    allowedAssistantTypes: [SALE, LEAD_CARE],
    allowedRoles: [Role.SALE],
    operation: 'READ_SUMMARY',
    dataScope: 'ASSIGNED_RECORDS',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['sales_dashboard', 'sale_lead_pipeline', 'sale_followups_due', 'sale_my_leads'],
    requiredEntities: [],
    contextPolicy: 'Doc summary pipeline truoc, chi nap danh sach lead gioi han khi user can drill-down.',
    missingDataPolicy: 'Neu khong co lead trong scope, noi ro va goi y kiem tra kho lead/phan bo lead.',
    writePolicy: 'Khong doi status/phan bo lead trong buoc doc.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'sale_order_pipeline_review',
    capability: 'SALES_CRM',
    userIntent: 'Sale hoi don hang cua minh, order cho duyet, can bo sung, da duyet va doanh thu order.',
    examples: ['Don nao cua toi can bo sung?', 'Order nao dang cho duyet?', 'Pipeline order cua toi?'],
    triggerKeywords: ['order cua toi', 'don cua toi', 'don hang cua toi', 'cho duyet', 'can bo sung', 'needs info', 'gui duyet', 'pipeline order', 'doanh thu order'],
    allowedAssistantTypes: [SALE],
    allowedRoles: [Role.SALE],
    operation: 'READ_DETAIL',
    dataScope: 'ASSIGNED_RECORDS',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['sales_dashboard', 'sale_order_pipeline', 'sale_my_orders'],
    requiredEntities: [],
    contextPolicy: 'Chi nap order trong scope sale; neu user hoi mot order cu the thi them order_detail.',
    missingDataPolicy: 'Neu khong co don trong filter, noi ro khoang ngay/trang thai dang dung va goi y mo rong filter.',
    writePolicy: 'Tao/sua/gui duyet/huy order can action draft, preview va xac nhan.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'sale_trial_followup',
    capability: 'SALES_CRM',
    userIntent: 'Sale hoi hoc thu/test cua minh, lich test, pending trial va waiting decision can chot.',
    examples: ['Hoc thu nao dang cho quyet dinh?', 'Buoi test cua toi hom nay?', 'Trial nao can chot sau test?'],
    triggerKeywords: ['hoc thu', 'trial', 'test', 'buoi test', 'lich test', 'cho quyet dinh', 'waiting decision', 'pending trial', 'chot sau test'],
    allowedAssistantTypes: [SALE, LEAD_CARE],
    allowedRoles: [Role.SALE],
    operation: 'READ_DETAIL',
    dataScope: 'ASSIGNED_RECORDS',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['sale_trial_summary', 'sale_trial_enrollments', 'sales_dashboard'],
    requiredEntities: [],
    contextPolicy: 'Doc summary hoc thu/test truoc, sau do danh sach gioi han 30 record trong scope sale.',
    missingDataPolicy: 'Neu khong co hoc thu/test, noi ro va goi y tao lich test tu lead/order phu hop.',
    writePolicy: 'Dat lich/cap nhat/chot ket qua hoc thu can preview va xac nhan.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'sale_commission_personal',
    capability: 'PAYROLL_COMPENSATION',
    userIntent: 'Sale hoi doanh thu ca nhan, hoa hong, commission va doi chieu order tinh hoa hong.',
    examples: ['Hoa hong cua toi thang nay?', 'Doanh thu ca nhan cua toi?', 'Commission theo order nao?'],
    triggerKeywords: ['hoa hong cua toi', 'commission cua toi', 'doanh thu cua toi', 'doanh so cua toi', 'tien hoa hong', 'bao cao hoa hong', 'thu nhap sale'],
    allowedAssistantTypes: [SALE],
    allowedRoles: [Role.SALE],
    operation: 'READ_SUMMARY',
    dataScope: 'OWN_RECORDS',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['sale_commission_report', 'sales_dashboard'],
    requiredEntities: [],
    contextPolicy: 'Chi lay hoa hong theo saleId tu JWT; khong cho hoi hoa hong cua sale khac.',
    missingDataPolicy: 'Neu chua co hoa hong, noi ro phu thuoc order approved/completed va khoang ngay dang xem.',
    writePolicy: 'Khong dieu chinh hoa hong/luong; tranh chap nen tao ticket hoac lien he ke toan.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'sale_pipeline_recovery_packet',
    capability: 'SALES_CRM',
    userIntent: 'Sale hoi goi phuc hoi pipeline lap lai: lead den han, lead nguoi, order ton va trial can chot.',
    examples: ['Pipeline cua toi dang ro ri o dau?', 'Lead/order/trial nao can cuu truoc?', 'Danh sach viec sale uu tien de chot doanh thu'],
    triggerKeywords: ['phuc hoi pipeline', 'pipeline ro ri', 'lead nguoi', 'lead stale', 'cuu lead', 'chot doanh thu', 'trial can chot', 'order ton'],
    allowedAssistantTypes: [SALE],
    allowedRoles: [Role.SALE],
    operation: 'READ_DETAIL',
    dataScope: 'ASSIGNED_RECORDS',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['sale_next_best_actions', 'sale_followups_due', 'sale_lead_pipeline', 'sale_my_leads', 'sale_order_pipeline'],
    requiredEntities: [],
    contextPolicy: 'Uu tien summary/follow-up queue; list lead chi lay gioi han va khong nap full conversation.',
    missingDataPolicy: 'Neu can noi dung cham soc ca nhan hoa, can lead_detail hoac conversation tool truoc khi soan message.',
    writePolicy: 'Cap nhat status/nextFollowUp/gui tin nhan can draft, preview va xac nhan.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'sale_revenue_commitment_packet',
    capability: 'SALES_CRM',
    userIntent: 'Sale hoi cam ket doanh thu ca nhan, order cho duyet/can bo sung, hoa hong va rui ro khong dat target.',
    examples: ['Doanh thu committed cua toi co dat khong?', 'Order nao can bo sung de tinh doanh thu?', 'Hoa hong va order thang nay co lech khong?'],
    triggerKeywords: ['cam ket doanh thu', 'committed revenue', 'target sale', 'khong dat target', 'order tinh doanh thu', 'doanh thu ca nhan', 'lech hoa hong'],
    allowedAssistantTypes: [SALE],
    allowedRoles: [Role.SALE],
    operation: 'READ_SUMMARY',
    dataScope: 'ASSIGNED_RECORDS',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['sale_next_best_actions', 'sales_dashboard', 'sale_order_pipeline', 'sale_my_orders', 'sale_commission_report'],
    requiredEntities: [],
    contextPolicy: 'Dung dashboard/order pipeline/commission summary; chi lay order list nho khi can bo sung ho so.',
    missingDataPolicy: 'Neu thieu target hoac commission rule, noi ro can cau hinh/bao cao bo sung thay vi uoc doan.',
    writePolicy: 'Khong sua hoa hong/order amount; tranh chap nen tao ticket tai chinh.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'operations_bottleneck',
    capability: 'LEARNING_OPERATIONS',
    userIntent: 'Hoi diem nghen van hanh: lop, buoi hoc, session, ticket, giao vien, hoc sinh.',
    examples: ['Van hanh co diem nghen nao?', 'Session nao chua chot?'],
    triggerKeywords: ['van hanh', 'ops', 'lop', 'class', 'buoi hoc', 'session', 'ticket', 'finalize', 'giao vien', 'hoc sinh'],
    allowedAssistantTypes: [DIRECTOR, OPS, TEACHER, PARENT],
    allowedRoles: [Role.DIRECTOR, Role.OPS, Role.TEACHER, Role.PARENT],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['daily_tasks', 'ops_dashboard', 'teacher_dashboard', 'parent_dashboard'],
    requiredEntities: [],
    contextPolicy: 'Chon dashboard phu hop role; khong nap danh sach lon.',
    missingDataPolicy: 'Neu can chi tiet session/lop/ticket, yeu cau drill-down co filter.',
    writePolicy: 'Khong chot/huy/doi lich trong buoc doc.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'ops_daily_sla_packet',
    capability: 'LEARNING_OPERATIONS',
    userIntent: 'OPS hoi packet dau ngay ve SLA, session can finalize/no-show, ticket mo va pending approval lien quan van hanh.',
    examples: ['OPS dau ngay can xu ly gi?', 'SLA nao dang do?', 'Session/ticket nao can uu tien?'],
    triggerKeywords: [
      'ops dau ngay',
      'hom nay van hanh',
      'van hanh can xu ly',
      'viec van hanh trong ngay',
      'uu tien van hanh',
      'ops can xu ly',
      'sla do',
      'sla van hanh',
      'session can finalize',
      'ticket mo uu tien',
      'goi van hanh',
      'ops packet',
    ],
    allowedAssistantTypes: [OPS],
    allowedRoles: [Role.OPS],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['ops_deep_sla_packet', 'daily_tasks', 'ops_dashboard', 'pending_approvals_summary', 'ops_guide'],
    requiredEntities: [],
    contextPolicy: 'Dung packet aggregate/queue da gioi han truoc; sap uu tien theo SLA/status/date va khong nap full history ticket/session.',
    missingDataPolicy: 'Neu can quyet dinh mot session/ticket, dung session_detail hoac ticket_detail truoc khi de xuat action.',
    writePolicy: 'Finalize/no-show/doi lich/resolve ticket can draft, preview va confirm.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'ops_pending_approval_detail',
    capability: 'ADMIN_SECURITY',
    userIntent: 'OPS hoi chi tiet hang cho duyet lien quan van hanh: invoice, top-up, giao vien, lop, doi lich.',
    examples: ['Cho toi xem cac muc cho duyet cua OPS', 'Giao vien/lop nao dang cho duyet?', 'Doi lich nao can duyet?'],
    triggerKeywords: ['cho duyet ops', 'pending approval ops', 'hang cho duyet van hanh', 'giao vien cho duyet', 'lop cho duyet', 'doi lich cho duyet', 'invoice cho duyet', 'topup cho duyet'],
    allowedAssistantTypes: [OPS],
    allowedRoles: [Role.OPS],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['pending_approval_invoices', 'pending_approval_topups', 'pending_approval_teachers', 'pending_approval_classes', 'pending_approval_session_changes'],
    requiredEntities: [],
    contextPolicy: 'Chi nap cac queue pending da limit; khong nap file chung tu hay execute phe duyet.',
    missingDataPolicy: 'Neu can quyet dinh mot record cu the, can invoice_detail/class_detail/session_detail hoac user detail truoc khi de xuat action.',
    writePolicy: 'Approve/reject moi loai pending can preview diff/ly do, confirm va audit.',
    riskLevel: 'HIGH',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'ops_attendance_reconciliation',
    capability: 'LEARNING_OPERATIONS',
    userIntent: 'OPS hoi diem danh, bao cao attendance, lop chua diem danh hoac sai lech giua attendance va session.',
    examples: ['Bao cao diem danh hom nay', 'Lop nao chua diem danh?', 'Attendance co sai lech gi voi session?'],
    triggerKeywords: ['diem danh', 'attendance', 'bao cao diem danh', 'lop chua diem danh', 'doi soat diem danh', 'attendance report', 'vang hoc'],
    allowedAssistantTypes: [OPS],
    allowedRoles: [Role.OPS],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['ops_attendance_report', 'ops_attendance_classes', 'ops_sessions', 'ops_classes', 'ops_guide'],
    requiredEntities: [],
    contextPolicy: 'Mac dinh hom nay; chi lay report/classes/session list da limit, khong nap lich su diem danh dai.',
    missingDataPolicy: 'Neu hoi mot lop/hoc sinh cu the, can classId/student_detail hoac filter truoc khi ket luan.',
    writePolicy: 'Mark/update/generate attendance link can draft, preview va confirm.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'ops_trial_test_control',
    capability: 'LEARNING_OPERATIONS',
    userIntent: 'OPS hoi hoc thu/test, slot giao vien trai nghiem, lich test va ho so can chot sau test.',
    examples: ['Hoc thu nao can dieu phoi?', 'Slot test nao con trong?', 'Buoi test nao dang waiting decision?'],
    triggerKeywords: ['hoc thu ops', 'trial ops', 'test ops', 'lich test', 'slot test', 'giao vien trai nghiem', 'waiting decision', 'buoi test'],
    allowedAssistantTypes: [OPS],
    allowedRoles: [Role.OPS],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['ops_trial_summary', 'ops_trial_enrollments', 'ops_trial_available_slots', 'ops_teacher_suggestions', 'ops_guide'],
    requiredEntities: [],
    contextPolicy: 'Lay summary truoc, sau do danh sach/slot gioi han; khong nap full lead/order history.',
    missingDataPolicy: 'Neu can dat/chot mot buoi test, can trial id va slot/giao vien ro rang truoc khi tao draft.',
    writePolicy: 'Dat lich/chot/convert/reject trial can preview va confirm.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'ops_work_sessions_control',
    capability: 'ADMIN_SECURITY',
    userIntent: 'OPS hoi phien lam viec, nhan su dang active, di muon/ve som va tong hop gio lam trong ky.',
    examples: ['Ai dang active?', 'Nhan su nao di muon thang nay?', 'Tong hop work sessions thang nay'],
    triggerKeywords: ['work session', 'phien lam viec', 'gio lam', 'di muon', 've som', 'dang active', 'cham cong noi bo'],
    allowedAssistantTypes: [OPS],
    allowedRoles: [Role.OPS],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['ops_work_sessions_summary', 'ops_work_sessions', 'ops_guide'],
    requiredEntities: [],
    contextPolicy: 'Summary theo ky va list limit; khong dung AI de chot payroll/cham cong chinh thuc.',
    missingDataPolicy: 'Neu can sua mot phien lam viec, can workSessionId, ly do va workflow edit rieng.',
    writePolicy: 'Sua gio/ghi chu work session can preview, ly do, confirm va audit.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'ops_student_teacher_onboarding',
    capability: 'HR_TEACHERS',
    userIntent: 'OPS hoi onboarding hoc sinh/giao vien: hoc sinh pending, giao vien pending, trang thai giao vien va viec can xu ly.',
    examples: ['Hoc sinh nao cho duyet?', 'Giao vien onboarding dang ton?', 'Teacher status co rui ro gi?'],
    triggerKeywords: ['onboarding', 'hoc sinh cho duyet', 'student pending', 'giao vien pending', 'teacher onboarding', 'duyet hoc sinh', 'duyet giao vien'],
    allowedAssistantTypes: [OPS],
    allowedRoles: [Role.OPS],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['ops_pending_students', 'pending_approval_teachers', 'ops_teacher_stats', 'ops_teachers', 'ops_guide'],
    requiredEntities: [],
    contextPolicy: 'Chi queue/status/list compact; khong nap day du ho so nhay cam neu chua can detail.',
    missingDataPolicy: 'Neu can duyet/sua mot hoc sinh/giao vien cu the, can student_detail hoac user/teacher detail truoc khi tao draft.',
    writePolicy: 'Approve/update/activate/suspend can preview, confirm va audit.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'ops_capacity_teacher_risk_packet',
    capability: 'HR_TEACHERS',
    userIntent: 'OPS hoi nang luc giao vien/lop, rui ro qua tai, lop thieu giao vien va hoc sinh bi anh huong.',
    examples: ['Lop nao co rui ro thieu giao vien?', 'Giao vien/lop nao dang qua tai?', 'Can dieu phoi lop nao truoc?'],
    triggerKeywords: ['thieu giao vien', 'giao vien qua tai', 'capacity giao vien', 'lop qua tai', 'dieu phoi lop', 'rui ro lop hoc', 'teacher capacity'],
    allowedAssistantTypes: [OPS],
    allowedRoles: [Role.OPS],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['ops_dashboard', 'ops_classes', 'ops_sessions', 'ops_teacher_suggestions', 'ops_teacher_stats'],
    requiredEntities: [],
    contextPolicy: 'Dung dashboard/class/session list co limit; khong tinh lich day thay ngoai data da co.',
    missingDataPolicy: 'Neu can quyet dinh gan giao vien cho mot lop cu the, can class_detail va teacher/user detail truoc khi de xuat action.',
    writePolicy: 'Doi giao vien, them co-teacher, sua lop hoac tao substitute request can preview va confirm.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'ops_class_session_control',
    capability: 'LEARNING_OPERATIONS',
    userIntent: 'OPS hoi lop, buoi hoc, lich, finalize/no-show/doi lich va diem nghen van hanh trong ngay.',
    examples: ['Session nao chua finalize?', 'Lop nao can can thiep?', 'Lich hoc hom nay co van de gi?'],
    triggerKeywords: ['session chua finalize', 'doi lich', 'huy buoi', 'no-show', 'lop active', 'lich hoc', 'diem nghen lop'],
    allowedAssistantTypes: [OPS],
    allowedRoles: [Role.OPS],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['daily_tasks', 'ops_dashboard', 'ops_sessions', 'ops_classes', 'ops_guide'],
    requiredEntities: [],
    contextPolicy: 'Lay dashboard/queue truoc, sau do session/class list gioi han theo ngay/thang.',
    missingDataPolicy: 'Neu hoi mot lop/buoi cu the, can class_detail hoac session_detail.',
    writePolicy: 'Doi/huy/finalize/no-show/sua lop can action draft, preview va confirm.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'teacher_daily_teaching_packet',
    capability: 'LEARNING_OPERATIONS',
    userIntent: 'Giao vien hoi goi dau ngay: lich day, buoi sap toi, bao cao con thieu va viec can chuan bi.',
    examples: ['Goi dau ngay cua giao vien', 'Hom nay toi can day/bao cao/chuan bi gi?', 'Buoi nao sap toi va bao cao nao con thieu?'],
    triggerKeywords: ['goi dau ngay giao vien', 'viec giao vien trong ngay', 'chuan bi buoi day', 'lich va bao cao', 'teaching packet'],
    allowedAssistantTypes: [TEACHER],
    allowedRoles: [Role.TEACHER],
    operation: 'READ_DETAIL',
    dataScope: 'OWN_RECORDS',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['daily_tasks', 'teacher_dashboard', 'teacher_upcoming_sessions', 'teacher_pending_reports', 'teacher_attendance_report'],
    requiredEntities: [],
    contextPolicy: 'Chi own records; uu tien upcoming sessions va pending reports, khong nap lich su dai.',
    missingDataPolicy: 'Neu khong co lich/pending report, noi ro khoang ngay/context dang dung.',
    writePolicy: 'Hoan thanh/huy/nop bao cao/gui ticket can preview va confirm.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'ops_ticket_sla_support',
    capability: 'SUPPORT_TICKETS',
    userIntent: 'OPS hoi ticket dang mo, ticket duoc gan, SLA qua han va viec ho tro can uu tien.',
    examples: ['Ticket nao qua SLA?', 'Ticket nao duoc gan cho toi?', 'Su co nao can xu ly truoc?'],
    triggerKeywords: ['ticket', 'sla', 'su co', 'assigned ticket', 'ticket duoc gan', 'resolve', 'request info', 'ho tro'],
    allowedAssistantTypes: [OPS],
    allowedRoles: [Role.OPS],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['daily_tasks', 'ops_open_tickets', 'ops_assigned_tickets', 'ops_dashboard', 'ops_guide'],
    requiredEntities: [],
    contextPolicy: 'Danh sach ticket phai limit, sap xep uu tien theo status/createdAt/SLA neu service co.',
    missingDataPolicy: 'Neu can chi tiet ticket, dung ticket_detail theo entity resolver.',
    writePolicy: 'Assign/comment/resolve/close ticket can preview va confirm.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'experience_teacher_quality_packet',
    capability: 'LEARNING_CONTENT',
    userIntent: 'Giao vien review hoi goi chat luong hoc tap: bai can cham, feedback can uu tien va rui ro chat luong noi dung.',
    examples: ['Bai nao can cham truoc?', 'Queue review co rui ro gi?', 'Can uu tien feedback nao?'],
    triggerKeywords: ['goi chat luong', 'quality packet', 'uu tien cham bai', 'rui ro chat luong', 'feedback hoc tap', 'queue review'],
    allowedAssistantTypes: [EXPERIENCE_TEACHER],
    allowedRoles: [Role.EXPERIENCE_TEACHER],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['homework_grading_queue', 'quiz_grading_queue', 'teaching_materials_search', 'teaching_material_chunks_search', 'teacher_guide'],
    requiredEntities: [],
    contextPolicy: 'Nap queue homework/quiz va hoc lieu/rubric chunk scoped o muc gioi han; khong nap file bai lam lon vao prompt.',
    missingDataPolicy: 'Neu can cham bai/quiz cu the, can detail entity hoac chunk hoc lieu READY truoc khi soan feedback.',
    writePolicy: 'AI chi soan nhan xet/draft diem; cham homework/quiz can action draft va xac nhan.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'teacher_schedule_sessions',
    capability: 'LEARNING_OPERATIONS',
    userIntent: 'Giao vien hoi lich day, buoi sap toi, lop/hoc sinh dang phu trach.',
    examples: ['Hom nay toi day lop nao?', 'Lich day sap toi cua toi?', 'Buoi hoc cua toi trong tuan nay?'],
    triggerKeywords: ['lich day', 'toi day', 'buoi sap toi', 'buoi hoc cua toi', 'lop cua toi', 'session cua toi', 'lich giao vien'],
    allowedAssistantTypes: [TEACHER],
    allowedRoles: [Role.TEACHER],
    operation: 'READ_DETAIL',
    dataScope: 'OWN_RECORDS',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['daily_tasks', 'teacher_dashboard', 'teacher_upcoming_sessions', 'teacher_my_sessions'],
    requiredEntities: [],
    contextPolicy: 'Chi nap lich/buoi hoc trong scope giao vien; uu tien SCHEDULED va lich gan nhat.',
    missingDataPolicy: 'Neu khong co buoi trong khoang ngay, noi ro khoang ngay dang dung va goi y doi filter.',
    writePolicy: 'Khong hoan thanh/huy/no-show trong buoc doc.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'teacher_attendance_support',
    capability: 'LEARNING_OPERATIONS',
    userIntent: 'Giao vien hoi diem danh, hoc sinh vang/muon, lop can diem danh hoac doi chieu attendance cua lop minh.',
    examples: ['Diem danh lop hom nay the nao?', 'Lop nao cua toi co hoc sinh vang?', 'Xem attendance cua lop A'],
    triggerKeywords: ['diem danh', 'attendance', 'hoc sinh vang', 'vang hoc', 'di muon', 'co mat', 'lop can diem danh'],
    allowedAssistantTypes: [TEACHER],
    allowedRoles: [Role.TEACHER],
    operation: 'READ_DETAIL',
    dataScope: 'OWN_RECORDS',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['teacher_attendance_classes', 'teacher_attendance_report', 'teacher_my_sessions', 'teacher_guide'],
    requiredEntities: [],
    contextPolicy: 'Chi doc diem danh/lop trong scope giao vien; neu khong co classId thi nap danh sach lop de goi y drill-down.',
    missingDataPolicy: 'Neu khong co attendance trong khoang ngay, noi ro khoang ngay va lop dang dung.',
    writePolicy: 'Danh dau/sua diem danh can preview va xac nhan, khong tu thuc hien trong buoc doc.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'teacher_material_preparation',
    capability: 'LEARNING_CONTENT',
    userIntent: 'Giao vien tim hoc lieu, slide, lesson plan, worksheet, bai tap hoac rubric de chuan bi buoi day.',
    examples: ['Tim hoc lieu cho buoi toi', 'Co worksheet nao ve fractions khong?', 'Chuan bi slide va bai tap cho lop cua toi'],
    triggerKeywords: ['hoc lieu', 'tai lieu day', 'slide', 'lesson plan', 'worksheet', 'rubric', 'bai tap', 'quiz', 'chuan bi bai', 'giao bai'],
    allowedAssistantTypes: [TEACHER],
    allowedRoles: [Role.TEACHER],
    operation: 'READ_DETAIL',
    dataScope: 'OWN_RECORDS',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['teacher_materials', 'teacher_material_stats', 'teacher_upcoming_sessions', 'teacher_guide'],
    requiredEntities: [],
    contextPolicy: 'Doc danh sach/meta hoc lieu trong scope; khong nap file lon, uu tien hoc lieu gan voi buoi sap toi neu co.',
    missingDataPolicy: 'Neu khong co hoc lieu phu hop, noi ro filter dang dung va goi y tao/tai len hoc lieu.',
    writePolicy: 'Tao/sua/giao hoc lieu hoac homework can workflow rieng va xac nhan.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'teacher_ticket_message_support',
    capability: 'SUPPORT_TICKETS',
    userIntent: 'Giao vien hoi ticket, su co, tin nhan chua doc, conversation ho tro hoac can tao yeu cau ho tro.',
    examples: ['Ticket cua toi dang den dau?', 'Toi co tin nhan nao chua doc?', 'Can tao ticket ho tro khong?'],
    triggerKeywords: ['ticket cua toi', 'ticket ho tro', 'su co', 'yeu cau ho tro', 'tin nhan', 'message', 'conversation', 'chua doc'],
    allowedAssistantTypes: [TEACHER],
    allowedRoles: [Role.TEACHER],
    operation: 'READ_DETAIL',
    dataScope: 'OWN_RECORDS',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['teacher_my_tickets', 'teacher_messages_unread', 'teacher_conversations', 'teacher_guide'],
    requiredEntities: [],
    contextPolicy: 'Chi doc ticket/conversation cua giao vien dang dang nhap; khong nap noi dung message chi tiet neu chua chi ro conversation.',
    missingDataPolicy: 'Neu khong co ticket/tin nhan, noi ro trong context da nap va goi y tao ticket khi co su co.',
    writePolicy: 'Tao/comment/resolve ticket hoac gui tin nhan can preview va xac nhan.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'teacher_report_queue',
    capability: 'LEARNING_OPERATIONS',
    userIntent: 'Giao vien hoi cac buoi can nop bao cao day hoac muon soan nhap bao cao.',
    examples: ['Buoi nao toi chua nop bao cao?', 'Can nop bao cao day nao?', 'Soan bao cao cho buoi nay'],
    triggerKeywords: ['bao cao day', 'chua nop bao cao', 'can nop bao cao', 'pending report', 'nop bao cao', 'soan bao cao', 'nhan xet hoc sinh'],
    allowedAssistantTypes: [TEACHER],
    allowedRoles: [Role.TEACHER],
    operation: 'READ_DETAIL',
    dataScope: 'OWN_RECORDS',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['daily_tasks', 'teacher_pending_reports', 'teacher_dashboard'],
    requiredEntities: [],
    contextPolicy: 'Lay queue bao cao con thieu trong scope giao vien; neu user chi ro buoi thi them session_detail.',
    missingDataPolicy: 'Neu khong tim thay buoi can bao cao, hoi lai ma buoi/lop/ngay hoac noi khong co pending report.',
    writePolicy: 'AI chi duoc soan nhap noi dung; nop/cap nhat bao cao day can preview va xac nhan.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'teacher_report_history',
    capability: 'LEARNING_OPERATIONS',
    userIntent: 'Giao vien xem lai bao cao day da nop, doi chieu noi dung va buoi hoc da hoan thanh.',
    examples: ['Bao cao toi da nop trong thang nay?', 'Xem lai bao cao day gan nhat', 'Buoi nao da co bao cao?'],
    triggerKeywords: ['bao cao da nop', 'da nop bao cao', 'lich su bao cao', 'xem lai bao cao', 'completed report'],
    allowedAssistantTypes: [TEACHER],
    allowedRoles: [Role.TEACHER],
    operation: 'READ_DETAIL',
    dataScope: 'OWN_RECORDS',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['teacher_completed_reports', 'teacher_dashboard'],
    requiredEntities: [],
    contextPolicy: 'Chi doc lich su bao cao cua giao vien dang dang nhap, limit 20.',
    missingDataPolicy: 'Neu khong co bao cao trong khoang ngay, noi ro va goi y mo rong filter.',
    writePolicy: 'Cap nhat bao cao da nop can preview va xac nhan.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'teacher_personal_payroll',
    capability: 'PAYROLL_COMPENSATION',
    userIntent: 'Giao vien hoi thu nhap, pending payout, bang luong gan nhat cua chinh minh.',
    examples: ['Luong cua toi thang nay?', 'Con bao nhieu pending payout?', 'Bang luong gan nhat cua toi?'],
    triggerKeywords: ['luong cua toi', 'thu nhap cua toi', 'pending payout', 'tien day', 'bang luong gan nhat', 'earnings'],
    allowedAssistantTypes: [TEACHER],
    allowedRoles: [Role.TEACHER],
    operation: 'READ_SUMMARY',
    dataScope: 'OWN_RECORDS',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['teacher_dashboard', 'teacher_payrolls', 'teacher_my_tickets'],
    requiredEntities: [],
    contextPolicy: 'Chi dung dashboard va payroll cua giao vien dang dang nhap, limit bang luong gan nhat.',
    missingDataPolicy: 'Neu khong co payroll/payout trong khoang ngay, noi ro va goi y mo rong filter hoac tao ticket khieu nai.',
    writePolicy: 'Khong de xuat duyet/tra/giu luong; moi khieu nai luong nen tao ticket.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'experience_teacher_homework_review',
    capability: 'LEARNING_CONTENT',
    userIntent: 'Giao vien review hoi queue bai tap can cham, bai da nop va huong dan cham/review.',
    examples: ['Bai nao can cham?', 'Queue homework grading?', 'Huong dan cham bai tap'],
    triggerKeywords: ['bai can cham', 'cham bai', 'homework grading', 'review bai tap', 'bai tap da nop', 'queue cham bai'],
    allowedAssistantTypes: [EXPERIENCE_TEACHER],
    allowedRoles: [Role.EXPERIENCE_TEACHER],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['homework_grading_queue', 'quiz_grading_queue', 'teaching_materials_search', 'teaching_material_chunks_search', 'teacher_guide'],
    requiredEntities: [],
    contextPolicy: 'Lay queue bai tap/quiz va hoc lieu/rubric scoped da limit; khong nap file lon vao prompt.',
    missingDataPolicy: 'Neu queue rong hoac thieu submission/rubric, noi ro chua du bang chung de cham.',
    writePolicy: 'AI chi soan nhan xet/draft diem; cham homework/quiz can action draft va xac nhan.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'parent_child_learning_finance',
    capability: 'LEARNING_OPERATIONS',
    userIntent: 'Phu huynh hoi lich hoc, tien do, bai tap, hoa don, vi va so buoi cua con.',
    examples: ['Tinh hinh hoc cua con toi?', 'Con toi con lich hoc nao?', 'Hoa don nao cua con toi chua thanh toan?', 'Hom nay toi can lam gi cho con?'],
    triggerKeywords: ['con toi', 'lich hoc cua con', 'tien do cua con', 'hoa don cua con', 'bai tap cua con', 'hoc phi', 'can lam gi cho con', 'tinh hinh cua con', 'hoc tap cua con'],
    allowedAssistantTypes: [PARENT],
    allowedRoles: [Role.PARENT],
    operation: 'READ_SUMMARY',
    dataScope: 'OWN_CHILDREN',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['parent_success_packet', 'parent_dashboard', 'student_learning_snapshot', 'parent_wallet_summary', 'parent_guide'],
    requiredEntities: [],
    contextPolicy: 'Dung parent_success_packet lam context chinh; chi du lieu cua phu huynh va con lien ket, finance chi invoice/wallet trong scope.',
    missingDataPolicy: 'Neu tai khoan chua lien ket hoc sinh, noi ro can cap nhat lien ket parent-student.',
    writePolicy: 'Khong thanh toan/doi lich tu dong; tao ticket/yeu cau can preview va confirm.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'parent_weekly_child_success_packet',
    capability: 'LEARNING_OPERATIONS',
    userIntent: 'Phu huynh hoi goi hang tuan ve lich hoc, tien do, bai tap, hoa don va viec can ho tro cho con.',
    examples: ['Bao cao hang tuan cua con toi', 'Tuan nay con can lam gi?', 'Con hoc the nao va co hoa don nao can xu ly?'],
    triggerKeywords: ['bao cao hang tuan cua con', 'weekly child', 'goi phu huynh hang tuan', 'tuan nay con can lam gi', 'tuan nay con', 'child success', 'ho tro cho con', 'ke hoach tuan nay cua con', 'viec can uu tien cho con'],
    allowedAssistantTypes: [PARENT],
    allowedRoles: [Role.PARENT],
    operation: 'READ_SUMMARY',
    dataScope: 'OWN_CHILDREN',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['parent_success_packet', 'student_learning_snapshot', 'parent_wallet_ledger', 'parent_my_tickets', 'parent_guide'],
    requiredEntities: [],
    contextPolicy: 'Chi own children; dung packet da tinh san, snapshot hoc tap, ledger/ticket da limit; khong nap finance ngoai scope.',
    missingDataPolicy: 'Neu chua link hoc sinh, noi ro can lien ket tai khoan truoc khi co brief.',
    writePolicy: 'Thanh toan/doi lich/tao ticket can workflow rieng va xac nhan.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'parent_support_ticket',
    capability: 'SUPPORT_TICKETS',
    userIntent: 'Phu huynh hoi ticket ho tro, can tao ticket doi lich/hoc phi/su co lop hoc.',
    examples: ['Ticket cua toi dang den dau?', 'Tao yeu cau doi lich cho con', 'Can hoi ve hoc phi'],
    triggerKeywords: ['ticket cua toi', 'yeu cau ho tro', 'doi lich', 'khieu nai', 'hoi hoc phi', 'can ho tro', 'phan anh', 'hoan tien', 'bao luu', 'nguoi that', 'nhan vien ho tro', 'giao vien vao muon'],
    allowedAssistantTypes: [PARENT],
    allowedRoles: [Role.PARENT],
    operation: 'READ_DETAIL',
    dataScope: 'OWN_RECORDS',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['parent_my_tickets', 'parent_success_packet', 'parent_my_sessions', 'parent_wallet_ledger', 'parent_guide'],
    requiredEntities: [],
    contextPolicy: 'Chi ticket cua phu huynh dang dang nhap; neu lien quan session/student thi can entity detail trong scope.',
    missingDataPolicy: 'Neu thieu noi dung bat buoc de tao ticket, hoi lai ro lop/buoi/hoc sinh/ly do.',
    writePolicy: 'Tao/comment ticket can preview va confirm.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'parent_wallet_ledger_detail',
    capability: 'INVOICE_WALLET',
    userIntent: 'Phu huynh hoi so du vi, lich su giao dich, top-up pending, tru tien buoi hoc, hoa don va cong no.',
    examples: ['Vi cua toi con bao nhieu?', 'Lich su giao dich vi thang nay?', 'Khoan nap tien cua toi da duyet chua?'],
    triggerKeywords: ['so du vi', 'vi cua toi', 'lich su giao dich', 'ledger', 'nap tien', 'top up', 'top-up', 'tru tien', 'hoan tien', 'cong no', 'thanh toan cua toi'],
    allowedAssistantTypes: [PARENT],
    allowedRoles: [Role.PARENT],
    operation: 'READ_DETAIL',
    dataScope: 'OWN_RECORDS',
    defaultWorkflow: 'READ_DETAIL',
    candidateTools: ['parent_wallet_summary', 'parent_wallet_ledger', 'parent_invoices', 'parent_success_packet', 'parent_guide'],
    requiredEntities: [],
    contextPolicy: 'Chi own wallet/ledger/invoices; khong nap chung tu/file va khong ket luan giao dich ngoai context.',
    missingDataPolicy: 'Neu khong co ledger trong khoang ngay, noi ro va goi y mo rong date range hoac tao ticket tai chinh.',
    writePolicy: 'Nap tien/hoan tien/dieu chinh so du can workflow rieng, preview va confirm.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'parent_attendance_schedule_risk',
    capability: 'LEARNING_OPERATIONS',
    userIntent: 'Phu huynh hoi diem danh, vang/muon, lich hoc gan toi hoac can doi soat buoi hoc cua con.',
    examples: ['Con toi vang buoi nao?', 'Thang nay con di muon may lan?', 'Diem danh cua con co bat thuong khong?'],
    triggerKeywords: ['diem danh cua con', 'vang hoc', 'di muon', 'tre gio', 'nghi hoc', 'attendance', 'xac nhan diem danh', 'lich hoc gan toi', 'buoi hoc gan toi'],
    allowedAssistantTypes: [PARENT],
    allowedRoles: [Role.PARENT],
    operation: 'READ_SUMMARY',
    dataScope: 'OWN_CHILDREN',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['parent_attendance_summary', 'parent_success_packet', 'parent_my_sessions', 'student_learning_snapshot', 'parent_guide'],
    requiredEntities: [],
    contextPolicy: 'Dung stats diem danh va record gan day lam bang chung; chi own children.',
    missingDataPolicy: 'Neu chua co diem danh trong khoang ngay, noi ro khong co record va goi y mo rong filter.',
    writePolicy: 'Khieu nai/xac nhan/sua diem danh can ticket hoac workflow rieng va confirm.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'parent_homework_materials_focus',
    capability: 'LEARNING_CONTENT',
    userIntent: 'Phu huynh hoi bai tap, quiz, hoc lieu, diem can on tap va feedback hoc tap cua con.',
    examples: ['Bai tap nao cua con chua xong?', 'Con can on phan nao?', 'Hoc lieu/quiz nao con can lam?'],
    triggerKeywords: ['bai tap cua con', 'bai tap nao', 'quiz cua con', 'hoc lieu cua con', 'can on phan nao', 'on tap', 'feedback hoc tap', 'nhan xet giao vien'],
    allowedAssistantTypes: [PARENT],
    allowedRoles: [Role.PARENT],
    operation: 'READ_SUMMARY',
    dataScope: 'OWN_CHILDREN',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['student_learning_snapshot', 'parent_success_packet', 'parent_children_progress', 'parent_my_sessions', 'parent_guide'],
    requiredEntities: [],
    contextPolicy: 'Dung learning snapshot truoc; khong nap file/hoc lieu raw, chi summary/metadata duoc phep.',
    missingDataPolicy: 'Neu chua co bai tap/hoc lieu/nhan xet, noi ro thay vi suy dien noi dung hoc.',
    writePolicy: 'Nop bai/lam quiz/gui feedback can workflow rieng va confirm.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'student_weekly_execution_packet',
    capability: 'LEARNING_CONTENT',
    userIntent: 'Hoc sinh hoi goi hoc tap lap lai: lich, bai tap, quiz, hoc lieu va viec can lam tiep trong tuan.',
    examples: ['Tuan nay em can lam gi?', 'Bai tap/quiz nao can uu tien?', 'Ke hoach hoc tap tuan nay'],
    triggerKeywords: ['tuan nay em', 'goi hoc tap', 'ke hoach hoc tap tuan', 'learning packet', 'bai tap quiz uu tien'],
    allowedAssistantTypes: [STUDENT],
    allowedRoles: [Role.STUDENT],
    operation: 'READ_SUMMARY',
    dataScope: 'OWN_RECORDS',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['student_learning_snapshot', 'student_guide'],
    requiredEntities: [],
    contextPolicy: 'Chi learning snapshot ca nhan; khong nap finance/phu huynh vao prompt.',
    missingDataPolicy: 'Neu chua co profile/link hoc sinh, noi ro can cap nhat ho so.',
    writePolicy: 'Nop quiz/bai tap can workflow rieng va confirm.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'student_learning_plan',
    capability: 'LEARNING_CONTENT',
    userIntent: 'Hoc sinh hoi lich hoc, bai tap, quiz, hoc lieu va diem can on tap tiep theo.',
    examples: ['Hom nay em can hoc gi?', 'Bai tap/quiz nao can lam?', 'Em can on phan nao?'],
    triggerKeywords: ['em can hoc gi', 'bai tap cua em', 'quiz cua em', 'lich hoc cua em', 'hoc lieu', 'on tap', 'tien do cua em'],
    allowedAssistantTypes: [STUDENT],
    allowedRoles: [Role.STUDENT],
    operation: 'READ_SUMMARY',
    dataScope: 'OWN_RECORDS',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['student_learning_snapshot', 'student_guide'],
    requiredEntities: [],
    contextPolicy: 'Chi nap learning snapshot cua hoc sinh dang dang nhap; khong nap finance cua phu huynh.',
    missingDataPolicy: 'Neu hoc sinh chua lien ket profile, noi ro can cap nhat ho so hoc sinh.',
    writePolicy: 'Nop quiz/bai tap can workflow rieng va confirm.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'ads_optimization_packet',
    capability: 'ADS_MARKETING',
    userIntent: 'Ads manager hoi goi toi uu lap lai: spend, CPL/CPO, ROI, ad group can can thiep va guardrail ngan sach.',
    examples: ['Quang cao nao can toi uu hom nay?', 'Ad group nao nen dung/theo doi?', 'Ngan sach ads co rui ro gi?'],
    triggerKeywords: ['toi uu ads', 'ads optimization', 'cpl', 'cpo', 'roi ads', 'ad group can dung', 'guardrail ngan sach', 'spend bat thuong'],
    allowedAssistantTypes: [ADS],
    allowedRoles: [Role.ADSMANAGER],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['ads_analytics_overview', 'ads_actions_required', 'ads_guide'],
    requiredEntities: [],
    contextPolicy: 'Dung analytics/actions-required da tinh san; khong nap token ads hay raw cost import.',
    missingDataPolicy: 'Neu chua co sync/cost/revenue attribution, noi ro metric nao thieu va de xuat sync/kiem tra tracking.',
    writePolicy: 'Dung/tang/giam ngan sach/sync token la high-risk action can preview, confirm va audit.',
    riskLevel: 'HIGH',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'ads_actions',
    capability: 'ADS_MARKETING',
    userIntent: 'Hoi hieu qua quang cao, campaign/ad group can can thiep, ngan sach.',
    examples: ['Quang cao nao can can thiep?', 'Co nen tang ngan sach campaign nao?'],
    triggerKeywords: ['ads', 'quang cao', 'marketing', 'campaign', 'ad group', 'ngan sach', 'facebook ads', 'google ads'],
    allowedAssistantTypes: [DIRECTOR, OPS, ADS],
    allowedRoles: [Role.DIRECTOR, Role.OPS, Role.ADSMANAGER],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['daily_tasks', 'ads_analytics_overview', 'ads_actions_required', 'ads_guide'],
    requiredEntities: [],
    contextPolicy: 'Chi lay suggestions da tinh san.',
    missingDataPolicy: 'Neu ads data chua dong bo, noi ro can sync/kiem tra token.',
    writePolicy: 'Khong doi ngan sach/token/sync khi chua confirm.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'shareholder_board_packet',
    capability: 'EXECUTIVE_OVERVIEW',
    userIntent: 'Co dong hoi packet hop board/investor lap lai: finance aggregate, runway, retention va rui ro tang truong khong PII.',
    examples: ['Packet hop co dong thang nay', 'Board update ve runway/retention/finance', 'Bao cao investor ngan gon'],
    triggerKeywords: ['packet co dong', 'board update', 'hop board', 'bao cao investor ngan gon', 'investor packet', 'cap nhat nha dau tu'],
    allowedAssistantTypes: [SHAREHOLDER],
    allowedRoles: [Role.SHAREHOLDER],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['shareholder_investor_metrics', 'financial_alerts', 'financial_overview', 'profit_and_loss', 'retention'],
    requiredEntities: [],
    contextPolicy: 'Chi aggregate/read-only, khong PII, khong audit/chat/user detail.',
    missingDataPolicy: 'Neu metric investor chua co, noi ro thieu metric va khong tu suy dien runway/unit economics.',
    writePolicy: 'Shareholder read-only; export/report pack can preview neu co workflow rieng.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'shareholder_investor_brief',
    capability: 'EXECUTIVE_OVERVIEW',
    userIntent: 'Co dong hoi bao cao aggregate, investor metrics, runway, burn rate, retention va chi so tang truong.',
    examples: ['Tinh hinh dau tu thang nay?', 'Runway va burn rate the nao?', 'Retention va finance aggregate ra sao?'],
    triggerKeywords: ['co dong', 'investor', 'runway', 'burn rate', 'unit economics', 'aggregate', 'bao cao dau tu', 'retention'],
    allowedAssistantTypes: [SHAREHOLDER],
    allowedRoles: [Role.SHAREHOLDER],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['shareholder_investor_metrics', 'financial_alerts', 'financial_overview', 'profit_and_loss', 'shareholder_guide'],
    requiredEntities: [],
    contextPolicy: 'Chi aggregate/read-only, mac dinh khong PII va khong audit/conversation noi bo chi tiet.',
    missingDataPolicy: 'Neu metric chua co, noi ro API hien co chua tra chi so do va de xuat bo sung investor metric.',
    writePolicy: 'Shareholder read-only, khong thao tac ghi.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'shareholder_finance_risk_packet',
    capability: 'FINANCE_CONTROL',
    userIntent: 'Co dong hoi red flags tai chinh: canh bao, cashflow, P&L, cong no, nghia vu va diem can hoi ban dieu hanh.',
    examples: ['Rui ro tai chinh lon nhat la gi?', 'Co red flag nao ve dong tien/cong no khong?', 'Nhung diem nao can hoi ban dieu hanh?'],
    triggerKeywords: ['rui ro tai chinh', 'red flag', 'red flags', 'canh bao tai chinh', 'dong tien rui ro', 'cong no rui ro', 'nghia vu tai chinh', 'cash risk', 'financial risk'],
    allowedAssistantTypes: [SHAREHOLDER],
    allowedRoles: [Role.SHAREHOLDER],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['shareholder_investor_metrics', 'financial_alerts', 'cash_flow', 'aging_report', 'profit_and_loss'],
    requiredEntities: [],
    contextPolicy: 'Chi aggregate/read-only; dung alert da tinh san, cashflow theo week, aging da mask va P&L tong hop.',
    missingDataPolicy: 'Neu thieu alert/cashflow/aging, noi ro metric nao chua nap duoc va khong suy dien nguyen nhan.',
    writePolicy: 'Shareholder read-only; chi dua cau hoi can hoi ban dieu hanh va follow-up can drill-down aggregate.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'shareholder_runway_sensitivity_packet',
    capability: 'FINANCE_CONTROL',
    userIntent: 'Co dong hoi runway, burn rate, kha nang chiu dung tien mat va kich ban stress neu chi phi/doanh thu thay doi.',
    examples: ['Neu burn rate tang thi runway con bao nhieu?', 'Cash runway co an toan khong?', 'Stress test dong tien thang nay'],
    triggerKeywords: ['runway sensitivity', 'stress test', 'kich ban xau', 'kich ban stress', 'burn rate tang thi runway', 'burn rate tang', 'runway con bao nhieu', 'runway giam', 'cash runway', 'chiu duoc bao lau', 'du tien bao lau'],
    allowedAssistantTypes: [SHAREHOLDER],
    allowedRoles: [Role.SHAREHOLDER],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['shareholder_investor_metrics', 'financial_alerts', 'cash_flow', 'financial_overview', 'profit_and_loss'],
    requiredEntities: [],
    contextPolicy: 'Dung cashOnHand, burnRate, runway, cashflow va P&L aggregate; neu tinh sensitivity thi noi ro do la uoc tinh tu metric da nap.',
    missingDataPolicy: 'Neu khong co burn/cashflow du tin cay, noi ro khong du co so stress test va de xuat metric can bo sung.',
    writePolicy: 'Khong dua lenh cat chi phi/chi tien; chi neu cau hoi follow-up va nguong can theo doi.',
    riskLevel: 'MEDIUM',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'shareholder_growth_retention_packet',
    capability: 'EXECUTIVE_OVERVIEW',
    userIntent: 'Co dong hoi tang truong, retention, churn, active/enrolled students va tin hieu cohort o muc aggregate.',
    examples: ['Tang truong va retention co dang xau di khong?', 'Churn co rui ro khong?', 'Active student co tang that khong?'],
    triggerKeywords: ['growth retention', 'tang truong retention', 'retention risk', 'churn risk', 'active student', 'enrolled student', 'hoc vien active', 'hoc vien roi', 'cohort retention'],
    allowedAssistantTypes: [SHAREHOLDER],
    allowedRoles: [Role.SHAREHOLDER],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['shareholder_investor_metrics', 'retention', 'financial_overview', 'profit_and_loss', 'shareholder_guide'],
    requiredEntities: [],
    contextPolicy: 'Chi aggregate; so sanh revenue trend, student trend, retention/churn va neu data caveat neu chua co cohort that.',
    missingDataPolicy: 'Neu chua co cohort-level retention, noi ro hien chi co aggregate retention/churn va de xuat bo sung cohort metric.',
    writePolicy: 'Khong can thiep hoc vien/lop; chi neu red flags va cau hoi can drill-down aggregate.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'shareholder_unit_economics_packet',
    capability: 'EXECUTIVE_OVERVIEW',
    userIntent: 'Co dong hoi CAC, CPL/CPO, LTV, LTV/CAC, ARPU va chat luong unit economics o muc aggregate.',
    examples: ['Unit economics co tot khong?', 'LTV/CAC co dat chuan khong?', 'CAC va ARPU dang noi len dieu gi?'],
    triggerKeywords: ['unit economics', 'ltv cac', 'ltv/cac', 'cac', 'cpl', 'cpo', 'cost per lead', 'cost per order', 'arpu', 'ltv', 'bien loi nhuan tren hoc vien'],
    allowedAssistantTypes: [SHAREHOLDER],
    allowedRoles: [Role.SHAREHOLDER],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['shareholder_investor_metrics', 'financial_overview', 'profit_and_loss', 'retention', 'shareholder_guide'],
    requiredEntities: [],
    contextPolicy: 'Dung aggregate methodology trong investor metrics; neu CAC/LTV la proxy thi phai ghi caveat ro rang.',
    missingDataPolicy: 'Neu thieu order/ads attribution, noi ro khong du ket luan CAC/LTV va can dong bo attribution.',
    writePolicy: 'Khong de xuat thay doi ngan sach ads nhu mot lenh; chi neu cau hoi ban dieu hanh can tra loi.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'shareholder_board_qna_packet',
    capability: 'EXECUTIVE_OVERVIEW',
    userIntent: 'Co dong can chuan bi cau hoi board Q&A: bang chung so lieu, diem yeu, caveat va follow-up khong PII.',
    examples: ['Nen hoi ban dieu hanh cau nao?', 'Chuan bi Q&A cho hop board', 'Cac cau hoi nha dau tu nen dat la gi?'],
    triggerKeywords: ['board q&a', 'q&a board', 'cau hoi board', 'cau hoi ban dieu hanh', 'hoi ban dieu hanh', 'nha dau tu nen hoi', 'chuan bi hop co dong'],
    allowedAssistantTypes: [SHAREHOLDER],
    allowedRoles: [Role.SHAREHOLDER],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['shareholder_investor_metrics', 'financial_alerts', 'retention', 'aging_report', 'shareholder_guide'],
    requiredEntities: [],
    contextPolicy: 'Tong hop thanh cau hoi board dua tren metric aggregate, alert, retention va aging da mask; khong dua PII.',
    missingDataPolicy: 'Neu context thieu, tao cau hoi ve metric can bo sung thay vi ket luan thay ban dieu hanh.',
    writePolicy: 'Khong ghi/export tu dong; chi soan cau hoi va checklist.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
  {
    key: 'teacher_or_parent_summary',
    capability: 'LEARNING_OPERATIONS',
    userIntent: 'Hoi lich, lop, tien do, viec ca nhan cua giao vien/phu huynh.',
    examples: ['Lich day cua toi?', 'Tinh hinh hoc cua con toi?'],
    triggerKeywords: ['lich day', 'lich hoc', 'con toi', 'lop cua toi', 'bao cao day', 'tien do', 'bai tap'],
    allowedAssistantTypes: [TEACHER, PARENT],
    allowedRoles: [Role.TEACHER, Role.PARENT],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    defaultWorkflow: 'READ_SUMMARY',
    candidateTools: ['daily_tasks', 'teacher_dashboard', 'parent_dashboard'],
    requiredEntities: [],
    contextPolicy: 'Chi own records/own children.',
    missingDataPolicy: 'Neu khong co du lieu lien ket, noi ro can cap nhat tai khoan/lien ket hoc sinh.',
    writePolicy: 'Khong nop/sua trong buoc doc.',
    riskLevel: 'LOW',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
  },
] as const;

export type AiCoreSituationKey = typeof AI_CORE_SITUATION_CATALOG[number]['key'];

export function getAiCoreSituationCatalog() {
  return AI_CORE_SITUATION_CATALOG;
}

export function getAiCoreSituationDefinition(key: string): AiSituationDefinition | undefined {
  return AI_CORE_SITUATION_CATALOG.find((situation) => situation.key === key);
}
