import { Role } from '../common/interfaces/role.enum';
import { AiAssistantType } from './schemas/ai-assistant-profile.schema';

export type AiErpOperation =
  | 'READ_SUMMARY'
  | 'READ_DETAIL'
  | 'CREATE'
  | 'UPDATE'
  | 'APPROVE'
  | 'REJECT'
  | 'WORKFLOW_ACTION'
  | 'EXPORT'
  | 'CONFIGURE';

export type AiErpDataScope =
  | 'GLOBAL'
  | 'ROLE_SCOPE'
  | 'OWN_RECORDS'
  | 'OWN_CHILDREN'
  | 'ASSIGNED_RECORDS'
  | 'PUBLIC_INTAKE'
  | 'NO_DATABASE';

export type AiErpRiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export interface AiErpSituationCatalogItem {
  key: string;
  group: string;
  userIntent: string;
  allowedAssistantTypes: readonly AiAssistantType[];
  allowedRoles: readonly Role[];
  apiRoutes: readonly string[];
  operation: AiErpOperation;
  dataScope: AiErpDataScope;
  contextPolicy: string;
  writePolicy: string;
  requiresConfirmation: boolean;
  requiresApproval: boolean;
  requiresAudit: boolean;
  riskLevel: AiErpRiskLevel;
}

export interface AiAssistantPermissionProfile {
  assistantType: AiAssistantType;
  label: string;
  primaryRoles: readonly Role[];
  dataBoundary: string;
  defaultContextPolicy: string;
  allowedOperations: readonly AiErpOperation[];
  forbidden: readonly string[];
}

const DIRECTOR = AiAssistantType.DIRECTOR_OPERATIONS;
const ACCOUNTING = AiAssistantType.ACCOUNTING_OPERATIONS;
const OPS = AiAssistantType.OPS_OPERATIONS;
const TEACHER = AiAssistantType.TEACHER_SUPPORT;
const EXPERIENCE_TEACHER = AiAssistantType.EXPERIENCE_TEACHER_SUPPORT;
const PARENT = AiAssistantType.PARENT_SUPPORT;
const STUDENT = AiAssistantType.STUDENT_SUPPORT;
const SALE = AiAssistantType.SALE_OPERATIONS;
const ADS = AiAssistantType.ADS_OPERATIONS;
const SHAREHOLDER = AiAssistantType.SHAREHOLDER_INSIGHTS;
const INTERNAL = AiAssistantType.INTERNAL_SUPPORT;
const LEAD_CARE = AiAssistantType.LEAD_CARE;

export const AI_ASSISTANT_PERMISSION_CATALOG = {
  [AiAssistantType.DIRECTOR_OPERATIONS]: {
    assistantType: AiAssistantType.DIRECTOR_OPERATIONS,
    label: 'Tro ly Giam doc',
    primaryRoles: [Role.DIRECTOR],
    dataBoundary: 'Toan he thong, nhung uu tien summary -> drill-down co gioi han.',
    defaultContextPolicy: 'Mac dinh nap daily tasks, pending approvals, dashboard/canh bao phu hop cau hoi.',
    allowedOperations: ['READ_SUMMARY', 'READ_DETAIL', 'CREATE', 'UPDATE', 'APPROVE', 'REJECT', 'WORKFLOW_ACTION', 'EXPORT', 'CONFIGURE'],
    forbidden: ['Khong tu thuc hien giao dich tien, xoa du lieu, gui thong bao hang loat neu chua co xac nhan 2 buoc.'],
  },
  [AiAssistantType.ACCOUNTING_OPERATIONS]: {
    assistantType: AiAssistantType.ACCOUNTING_OPERATIONS,
    label: 'Tro ly Ke toan',
    primaryRoles: [Role.ACCOUNTING],
    dataBoundary: 'Tai chinh, hoa don, vi, payroll, cong no, export tai chinh.',
    defaultContextPolicy: 'Chi nap dashboard/accounting, financial-control va hang cho duyet tai chinh.',
    allowedOperations: ['READ_SUMMARY', 'READ_DETAIL', 'CREATE', 'UPDATE', 'APPROVE', 'REJECT', 'WORKFLOW_ACTION', 'EXPORT'],
    forbidden: ['Khong xem prompt/token AI', 'Khong quan tri user he thong', 'Khong xoa du lieu.'],
  },
  [AiAssistantType.OPS_OPERATIONS]: {
    assistantType: AiAssistantType.OPS_OPERATIONS,
    label: 'Tro ly Van hanh',
    primaryRoles: [Role.OPS],
    dataBoundary: 'Lop, session, ticket, hoc sinh, giao vien va queue van hanh.',
    defaultContextPolicy: 'Nap ops dashboard, daily tasks, sessions/classes/tickets theo filter ngay va trang thai.',
    allowedOperations: ['READ_SUMMARY', 'READ_DETAIL', 'CREATE', 'UPDATE', 'APPROVE', 'REJECT', 'WORKFLOW_ACTION', 'EXPORT'],
    forbidden: ['Khong thay doi so du vi, khong duyet chi tien/luong, khong quan tri AI token.'],
  },
  [AiAssistantType.TEACHER_SUPPORT]: {
    assistantType: AiAssistantType.TEACHER_SUPPORT,
    label: 'Tro ly giao vien',
    primaryRoles: [Role.TEACHER],
    dataBoundary: 'Chi du lieu cua giao vien dang dang nhap: lich day, lop, bao cao, bai tap, ticket cua minh.',
    defaultContextPolicy: 'Nap my-sessions, pending-report, dashboard teacher; khong nap danh sach giao vien/hoc sinh toan he thong.',
    allowedOperations: ['READ_SUMMARY', 'READ_DETAIL', 'CREATE', 'UPDATE', 'WORKFLOW_ACTION'],
    forbidden: ['Khong xem luong nguoi khac', 'Khong xem session/lop khong duoc phan cong', 'Khong phe duyet tai chinh.'],
  },
  [AiAssistantType.EXPERIENCE_TEACHER_SUPPORT]: {
    assistantType: AiAssistantType.EXPERIENCE_TEACHER_SUPPORT,
    label: 'Tro ly giao vien review',
    primaryRoles: [Role.EXPERIENCE_TEACHER],
    dataBoundary: 'Bai tap/bai review va hoc lieu trong pham vi duoc giao.',
    defaultContextPolicy: 'Nap homework grading, material/quiz tools theo filter nho.',
    allowedOperations: ['READ_SUMMARY', 'READ_DETAIL', 'UPDATE', 'WORKFLOW_ACTION'],
    forbidden: ['Khong xem tai chinh', 'Khong sua session ngoai pham vi review.'],
  },
  [AiAssistantType.PARENT_SUPPORT]: {
    assistantType: AiAssistantType.PARENT_SUPPORT,
    label: 'Cham soc phu huynh',
    primaryRoles: [Role.PARENT],
    dataBoundary: 'Chi du lieu cua phu huynh va cac con lien ket.',
    defaultContextPolicy: 'Nap parent dashboard, my-children sessions, invoices, wallet va tickets cua phu huynh.',
    allowedOperations: ['READ_SUMMARY', 'READ_DETAIL', 'CREATE', 'UPDATE', 'WORKFLOW_ACTION'],
    forbidden: ['Khong xem phu huynh/hoc sinh khac', 'Khong tu huy/doi lich neu can quy trinh xac nhan.'],
  },
  [AiAssistantType.STUDENT_SUPPORT]: {
    assistantType: AiAssistantType.STUDENT_SUPPORT,
    label: 'Ho tro hoc sinh',
    primaryRoles: [Role.STUDENT],
    dataBoundary: 'Chi lich hoc, bai tap, quiz va noi dung hoc tap cua hoc sinh dang dang nhap.',
    defaultContextPolicy: 'Chi nap hoc lieu, quiz, bai tap va thong tin lich hoc ca nhan.',
    allowedOperations: ['READ_SUMMARY', 'READ_DETAIL', 'CREATE', 'UPDATE'],
    forbidden: ['Khong xem tai chinh phu huynh', 'Khong xem thong tin hoc sinh khac.'],
  },
  [AiAssistantType.SALE_OPERATIONS]: {
    assistantType: AiAssistantType.SALE_OPERATIONS,
    label: 'Tro ly Sales',
    primaryRoles: [Role.SALE],
    dataBoundary: 'Lead/order/conversation/sessions lien quan sale dang dang nhap hoac scope ERP cho SALE.',
    defaultContextPolicy: 'Nap sales dashboard theo saleId, lead follow-ups, order pipeline va conversation dang xu ly.',
    allowedOperations: ['READ_SUMMARY', 'READ_DETAIL', 'CREATE', 'UPDATE', 'WORKFLOW_ACTION'],
    forbidden: ['Khong xem P&L day du', 'Khong duyet hoa don/nap tien', 'Khong assign lead neu API yeu cau OPS/DIRECTOR.'],
  },
  [AiAssistantType.ADS_OPERATIONS]: {
    assistantType: AiAssistantType.ADS_OPERATIONS,
    label: 'Tro ly Ads',
    primaryRoles: [Role.ADSMANAGER],
    dataBoundary: 'Tai khoan quang cao, ad cost, analytics, suggestions va conversation lien quan marketing.',
    defaultContextPolicy: 'Nap ads analytics/actions-required; token va sync chi doc/ghi theo API role hien co.',
    allowedOperations: ['READ_SUMMARY', 'READ_DETAIL', 'CREATE', 'UPDATE', 'WORKFLOW_ACTION'],
    forbidden: ['Khong thay doi ngan sach/chay sync/doi token neu chua xac nhan.'],
  },
  [AiAssistantType.SHAREHOLDER_INSIGHTS]: {
    assistantType: AiAssistantType.SHAREHOLDER_INSIGHTS,
    label: 'Bao cao co dong',
    primaryRoles: [Role.SHAREHOLDER],
    dataBoundary: 'Chi bao cao tong hop duoc phep: retention, financial overview, investor/export lien quan co dong.',
    defaultContextPolicy: 'Chi nap aggregate, khong nap danh sach ca nhan/PII neu khong can.',
    allowedOperations: ['READ_SUMMARY', 'READ_DETAIL', 'EXPORT'],
    forbidden: ['Khong thao tac ghi', 'Khong xem audit/user/chat noi bo chi tiet.'],
  },
  [AiAssistantType.INTERNAL_SUPPORT]: {
    assistantType: AiAssistantType.INTERNAL_SUPPORT,
    label: 'Ho tro noi bo',
    primaryRoles: [Role.DIRECTOR, Role.OPS, Role.ACCOUNTING, Role.SALE, Role.ADSMANAGER],
    dataBoundary: 'Ho tro quy trinh va tra cuu he thong theo role dang dang nhap.',
    defaultContextPolicy: 'Khong mac dinh nap du lieu nhay cam; chi doc guide va tool duoc role cho phep.',
    allowedOperations: ['READ_SUMMARY', 'READ_DETAIL', 'CREATE', 'UPDATE', 'WORKFLOW_ACTION'],
    forbidden: ['Khong vuot role cua nguoi dung dang dang nhap.'],
  },
  [AiAssistantType.LEAD_CARE]: {
    assistantType: AiAssistantType.LEAD_CARE,
    label: 'Cham soc lead',
    primaryRoles: [Role.SALE, Role.OPS, Role.DIRECTOR],
    dataBoundary: 'Lead, conversation va order trong pipeline cham soc.',
    defaultContextPolicy: 'Nap context hoi thoai hien tai, lead lien quan va san pham/goi hoc can tu van.',
    allowedOperations: ['READ_SUMMARY', 'READ_DETAIL', 'CREATE', 'UPDATE', 'WORKFLOW_ACTION'],
    forbidden: ['Khong tao cam ket hoc phi/khuyen mai ngoai products/orders duoc phep.'],
  },
} as const satisfies Record<AiAssistantType, AiAssistantPermissionProfile>;

export const AI_ERP_SITUATION_CATALOG: readonly AiErpSituationCatalogItem[] = [
  {
    key: 'daily_work_queue',
    group: 'Daily operations',
    userIntent: 'Hoi hom nay can lam gi, viec nao qua han, uu tien nao can xu ly.',
    allowedAssistantTypes: [DIRECTOR, ACCOUNTING, OPS, TEACHER, EXPERIENCE_TEACHER, PARENT, SALE, ADS, INTERNAL],
    allowedRoles: [Role.DIRECTOR, Role.ACCOUNTING, Role.OPS, Role.TEACHER, Role.EXPERIENCE_TEACHER, Role.PARENT, Role.SALE, Role.ADSMANAGER],
    apiRoutes: ['GET /dashboard/daily-tasks'],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Luon la context dau tien; chi lay board da service gioi han theo role/user.',
    writePolicy: 'Chi de xuat hanh dong tiep theo.',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
    riskLevel: 'LOW',
  },
  {
    key: 'director_overview_and_risks',
    group: 'Director overview',
    userIntent: 'Tong quan doanh nghiep, rui ro, viec can can thiep cap giam doc.',
    allowedAssistantTypes: [DIRECTOR],
    allowedRoles: [Role.DIRECTOR],
    apiRoutes: ['GET /dashboard/director', 'GET /pending-approvals/summary', 'GET /financial-control/alerts', 'GET /audit-log/stats'],
    operation: 'READ_SUMMARY',
    dataScope: 'GLOBAL',
    contextPolicy: 'Mac dinh thang hien tai; chi aggregate/recent limit.',
    writePolicy: 'Chi de xuat, khong tu approve/reject.',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
    riskLevel: 'MEDIUM',
  },
  {
    key: 'accounting_financial_overview',
    group: 'Finance',
    userIntent: 'Hoi tinh hinh tai chinh, dong tien, P&L, cong no, canh bao.',
    allowedAssistantTypes: [DIRECTOR, ACCOUNTING, SHAREHOLDER],
    allowedRoles: [Role.DIRECTOR, Role.ACCOUNTING, Role.SHAREHOLDER],
    apiRoutes: ['GET /dashboard/accounting', 'GET /financial-control/overview', 'GET /financial-control/cash-flow', 'GET /financial-control/profit-loss', 'GET /financial-control/aging'],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Dung aggregate theo ngay; shareholder chi xem aggregate khong PII.',
    writePolicy: 'Khong thuc hien giao dich tien trong buoc doc.',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
    riskLevel: 'MEDIUM',
  },
  {
    key: 'invoice_read_and_management',
    group: 'Invoices',
    userIntent: 'Tra cuu hoa don, hoa don cho duyet, cong no hoc vien/phu huynh.',
    allowedAssistantTypes: [DIRECTOR, ACCOUNTING, OPS, SALE, PARENT],
    allowedRoles: [Role.DIRECTOR, Role.ACCOUNTING, Role.OPS, Role.SALE, Role.PARENT],
    apiRoutes: ['GET /invoices', 'GET /invoices/management', 'GET /invoices/pending', 'GET /invoices/my-children', 'GET /invoices/:id'],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Parent chi own children; sale/ops/accounting theo service scope; limit + filter bat buoc khi list.',
    writePolicy: 'Khong sua/duyet trong buoc doc.',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
    riskLevel: 'MEDIUM',
  },
  {
    key: 'invoice_write_actions',
    group: 'Invoices',
    userIntent: 'Tao, sua, duyet, tu choi, huy hoa don, xac nhan thanh toan.',
    allowedAssistantTypes: [DIRECTOR, ACCOUNTING, SALE],
    allowedRoles: [Role.DIRECTOR, Role.ACCOUNTING, Role.SALE],
    apiRoutes: ['POST /invoices', 'PATCH /invoices/:id', 'POST /invoices/:id/approve', 'POST /invoices/:id/cancel', 'POST /invoices/payments/:studentId/:frameIndex/confirm'],
    operation: 'APPROVE',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Phai lay chi tiet invoice va lien quan wallet/order truoc khi de xuat.',
    writePolicy: 'Can preview payload, ly do, nguoi xac nhan; cancel/approve bat buoc audit.',
    requiresConfirmation: true,
    requiresApproval: true,
    requiresAudit: true,
    riskLevel: 'CRITICAL',
  },
  {
    key: 'wallet_and_ledger_read',
    group: 'Wallets',
    userIntent: 'Tra so du vi, lich su giao dich, top-up pending, doi soat.',
    allowedAssistantTypes: [DIRECTOR, ACCOUNTING, OPS, PARENT],
    allowedRoles: [Role.DIRECTOR, Role.ACCOUNTING, Role.OPS, Role.PARENT],
    apiRoutes: ['GET /wallets/me', 'GET /wallets', 'GET /wallets/user/:userId', 'GET /wallets/ledger', 'GET /wallets/me/ledger', 'GET /wallets/top-up/pending', 'GET /wallets/stats/financial'],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Parent chi wallet/ledger cua minh; internal list phai co limit/filter.',
    writePolicy: 'Khong doi so du trong buoc doc.',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
    riskLevel: 'MEDIUM',
  },
  {
    key: 'wallet_money_write_actions',
    group: 'Wallets',
    userIntent: 'Duyet nap tien, tu choi nap tien, dieu chinh so du, chuyen tien, khoa/mo vi.',
    allowedAssistantTypes: [DIRECTOR, ACCOUNTING],
    allowedRoles: [Role.DIRECTOR, Role.ACCOUNTING],
    apiRoutes: ['POST /wallets/top-up/:id/approve', 'POST /wallets/top-up/:id/reject', 'POST /wallets/adjust', 'POST /wallets/transfer', 'POST /wallets/user/:userId/freeze', 'POST /wallets/user/:userId/unfreeze', 'POST /wallets/verify-balances'],
    operation: 'WORKFLOW_ACTION',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Phai lay top-up/wallet/ledger lien quan truoc, so sanh so tien va chung tu.',
    writePolicy: 'Bat buoc xac nhan 2 buoc, ly do, audit va idempotency khi trien khai write tool.',
    requiresConfirmation: true,
    requiresApproval: true,
    requiresAudit: true,
    riskLevel: 'CRITICAL',
  },
  {
    key: 'payroll_and_salary',
    group: 'Payroll',
    userIntent: 'Tinh luong, xem payroll, giu/duyet/tra luong, cau hinh luong.',
    allowedAssistantTypes: [DIRECTOR, ACCOUNTING, OPS, TEACHER],
    allowedRoles: [Role.DIRECTOR, Role.ACCOUNTING, Role.OPS, Role.TEACHER],
    apiRoutes: ['GET /payroll', 'GET /payroll/:id', 'POST /payroll/*', 'GET /salary-config', 'PATCH /salary-config/*'],
    operation: 'WORKFLOW_ACTION',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Teacher chi xem thong tin cua minh; accounting/director xem aggregate va chi tiet can filter.',
    writePolicy: 'Duyet/tra/giu luong la high risk, bat buoc preview + confirm + audit.',
    requiresConfirmation: true,
    requiresApproval: true,
    requiresAudit: true,
    riskLevel: 'CRITICAL',
  },
  {
    key: 'sessions_read',
    group: 'Learning operations',
    userIntent: 'Xem lich hoc, buoi hoc, session pending report, homework grading, progress.',
    allowedAssistantTypes: [DIRECTOR, ACCOUNTING, OPS, TEACHER, EXPERIENCE_TEACHER, PARENT, SALE, SHAREHOLDER],
    allowedRoles: [Role.DIRECTOR, Role.ACCOUNTING, Role.OPS, Role.TEACHER, Role.EXPERIENCE_TEACHER, Role.PARENT, Role.SALE, Role.SHAREHOLDER],
    apiRoutes: ['GET /sessions', 'GET /sessions/stats', 'GET /sessions/my-sessions', 'GET /sessions/my-children', 'GET /sessions/my-children/progress', 'GET /sessions/homework-grading', 'GET /sessions/:id'],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Teacher/parent/sale bi service ep owner scope; internal phai filter date/status va limit.',
    writePolicy: 'Khong thay doi session trong buoc doc.',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
    riskLevel: 'MEDIUM',
  },
  {
    key: 'sessions_workflow_actions',
    group: 'Learning operations',
    userIntent: 'Tao buoi hoc, hoan thanh, xac nhan, finalize, huy, doi lich, no-show, review change request.',
    allowedAssistantTypes: [DIRECTOR, ACCOUNTING, OPS, TEACHER, PARENT, SALE],
    allowedRoles: [Role.DIRECTOR, Role.ACCOUNTING, Role.OPS, Role.TEACHER, Role.PARENT, Role.SALE],
    apiRoutes: ['POST /sessions', 'POST /sessions/bulk', 'POST /sessions/:id/complete', 'POST /sessions/:id/confirm', 'POST /sessions/:id/finalize', 'POST /sessions/:id/cancel', 'POST /sessions/:id/reschedule', 'POST /sessions/:id/no-show', 'POST /sessions/change-requests/:requestId/review'],
    operation: 'WORKFLOW_ACTION',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Phai doc session chi tiet va trang thai hien tai truoc khi de xuat action.',
    writePolicy: 'Can xac nhan; huy/doi lich/finalize/no-show can ly do va audit.',
    requiresConfirmation: true,
    requiresApproval: true,
    requiresAudit: true,
    riskLevel: 'HIGH',
  },
  {
    key: 'teaching_report_and_homework',
    group: 'Teaching',
    userIntent: 'Nop bao cao day, nop/cham/review bai tap, xem teaching report.',
    allowedAssistantTypes: [DIRECTOR, OPS, TEACHER, EXPERIENCE_TEACHER, PARENT],
    allowedRoles: [Role.DIRECTOR, Role.OPS, Role.TEACHER, Role.EXPERIENCE_TEACHER, Role.PARENT],
    apiRoutes: ['PATCH /sessions/:id/teaching-report', 'PATCH /sessions/bulk-teaching-report', 'POST /sessions/:id/homework-submit', 'PATCH /sessions/:id/homework-grade', 'POST /sessions/:id/homework-review', 'GET /reports/teaching'],
    operation: 'UPDATE',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Teacher chi sessions cua minh; parent chi bai cua con; reviewer chi queue grading.',
    writePolicy: 'AI co the soan noi dung, nhung nguoi dung phai xac nhan truoc khi nop/cham.',
    requiresConfirmation: true,
    requiresApproval: false,
    requiresAudit: true,
    riskLevel: 'HIGH',
  },
  {
    key: 'attendance',
    group: 'Attendance',
    userIntent: 'Diem danh, xem lich su diem danh, phu huynh xem diem danh con.',
    allowedAssistantTypes: [DIRECTOR, OPS, TEACHER, PARENT],
    allowedRoles: [Role.DIRECTOR, Role.OPS, Role.TEACHER, Role.PARENT],
    apiRoutes: ['GET /attendance/*', 'POST /attendance/*', 'PATCH /attendance/*'],
    operation: 'UPDATE',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Teacher/parent chi scope lien quan; internal filter theo class/session/date.',
    writePolicy: 'Diem danh/sua diem danh can xac nhan va ly do neu sua sau gio.',
    requiresConfirmation: true,
    requiresApproval: false,
    requiresAudit: true,
    riskLevel: 'HIGH',
  },
  {
    key: 'classes_students_teachers',
    group: 'Academic master data',
    userIntent: 'Tra cuu/sua lop, hoc sinh, giao vien, phan cong, phe duyet thay doi lop/giao vien.',
    allowedAssistantTypes: [DIRECTOR, OPS, ACCOUNTING, SALE, TEACHER, PARENT, EXPERIENCE_TEACHER],
    allowedRoles: [Role.DIRECTOR, Role.OPS, Role.ACCOUNTING, Role.SALE, Role.TEACHER, Role.PARENT, Role.EXPERIENCE_TEACHER],
    apiRoutes: ['GET /classes', 'POST /classes', 'PATCH /classes/:id', 'GET /students', 'PATCH /students/:id', 'GET /teachers', 'PATCH /teachers/:id', 'GET /teacher-registrations'],
    operation: 'UPDATE',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Parent/teacher chi du lieu lien quan; sale/ops xem theo service scope; list can limit.',
    writePolicy: 'Tao/sua/phe duyet can preview truoc; thay doi giao vien/lop can audit.',
    requiresConfirmation: true,
    requiresApproval: true,
    requiresAudit: true,
    riskLevel: 'HIGH',
  },
  {
    key: 'lead_pipeline',
    group: 'Sales',
    userIntent: 'Theo doi lead, follow-up, pipeline, pool, cham soc lead.',
    allowedAssistantTypes: [DIRECTOR, OPS, SALE, LEAD_CARE],
    allowedRoles: [Role.DIRECTOR, Role.OPS, Role.SALE],
    apiRoutes: ['GET /leads', 'GET /leads/pipeline', 'GET /leads/stats', 'GET /leads/follow-ups', 'GET /leads/pool/list', 'GET /chatbot/conversations'],
    operation: 'READ_DETAIL',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Sale chi scope sale duoc service cho phep; director/ops co the xem tong hop.',
    writePolicy: 'Khong tu gan/chuyen doi lead khi chua xac nhan.',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
    riskLevel: 'MEDIUM',
  },
  {
    key: 'lead_and_order_actions',
    group: 'Sales',
    userIntent: 'Tao/cap nhat lead, ghi nhan lien he, convert, lost, assign, tao/order, approve/reject order.',
    allowedAssistantTypes: [DIRECTOR, OPS, SALE, LEAD_CARE],
    allowedRoles: [Role.DIRECTOR, Role.OPS, Role.SALE],
    apiRoutes: ['POST /leads', 'PATCH /leads/:id', 'POST /leads/:id/contact', 'POST /leads/:id/convert', 'POST /leads/:id/lost', 'POST /leads/:id/assign', 'POST /orders', 'POST /orders/:id/approve', 'POST /orders/:id/reject'],
    operation: 'WORKFLOW_ACTION',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Phai doc lead/order hien tai va conversation lien quan truoc khi de xuat.',
    writePolicy: 'Can confirm payload; approve/reject order can can DIRECTOR/OPS tuy route.',
    requiresConfirmation: true,
    requiresApproval: true,
    requiresAudit: true,
    riskLevel: 'HIGH',
  },
  {
    key: 'trial_enrollment_and_products',
    group: 'Sales',
    userIntent: 'Quan ly hoc thu, san pham/goi hoc, khuyen nghi goi hoc.',
    allowedAssistantTypes: [DIRECTOR, OPS, SALE, EXPERIENCE_TEACHER, LEAD_CARE],
    allowedRoles: [Role.DIRECTOR, Role.OPS, Role.SALE, Role.EXPERIENCE_TEACHER],
    apiRoutes: ['GET /trial-enrollments', 'POST /trial-enrollments/*', 'GET /products', 'POST /products', 'PATCH /products/:id'],
    operation: 'WORKFLOW_ACTION',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Products co the doc de tu van; sua gia/goi hoc chi role duoc phep.',
    writePolicy: 'Thay doi hoc thu/san pham/gia can confirm va audit.',
    requiresConfirmation: true,
    requiresApproval: true,
    requiresAudit: true,
    riskLevel: 'HIGH',
  },
  {
    key: 'tickets_support',
    group: 'Support',
    userIntent: 'Tao ticket, xem ticket, comment, nhan xu ly, yeu cau thong tin, resolve, close, reopen.',
    allowedAssistantTypes: [DIRECTOR, OPS, ACCOUNTING, TEACHER, PARENT, INTERNAL],
    allowedRoles: [Role.DIRECTOR, Role.OPS, Role.ACCOUNTING, Role.TEACHER, Role.PARENT],
    apiRoutes: ['GET /tickets', 'GET /tickets/my-tickets', 'GET /tickets/:id', 'POST /tickets', 'POST /tickets/:id/comments', 'POST /tickets/:id/resolve', 'POST /tickets/:id/close', 'POST /tickets/:id/reopen'],
    operation: 'WORKFLOW_ACTION',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Parent/teacher chi ticket cua minh; internal co the xem internal comments theo role.',
    writePolicy: 'Resolve/refund/close can confirm; internal comments khong hien cho PH/GV.',
    requiresConfirmation: true,
    requiresApproval: false,
    requiresAudit: true,
    riskLevel: 'HIGH',
  },
  {
    key: 'ads_analytics_and_actions',
    group: 'Ads',
    userIntent: 'Phan tich quang cao, loi nhuan campaign/ad group, de xuat tang/giam ngan sach.',
    allowedAssistantTypes: [DIRECTOR, ADS, OPS, SALE, SHAREHOLDER],
    allowedRoles: [Role.DIRECTOR, Role.ADSMANAGER, Role.OPS, Role.SALE, Role.SHAREHOLDER],
    apiRoutes: ['GET /ads/analytics', 'GET /ads/analytics/actions-required', 'GET /ads/analytics/suggestions', 'GET /ads/accounts', 'GET /ads/ad-groups'],
    operation: 'READ_SUMMARY',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Dung aggregate analytics; shareholder chi aggregate khong PII.',
    writePolicy: 'Chi de xuat, khong tu doi ngan sach/token/sync.',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: true,
    riskLevel: 'MEDIUM',
  },
  {
    key: 'ads_configuration_and_sync',
    group: 'Ads',
    userIntent: 'Tao/sua ad account, token, sync cost, cap nhat ad group.',
    allowedAssistantTypes: [DIRECTOR, ADS],
    allowedRoles: [Role.DIRECTOR, Role.ADSMANAGER],
    apiRoutes: ['POST /ads/accounts', 'PATCH /ads/accounts/:id', 'POST /ads/tokens', 'PATCH /ads/tokens/:id', 'POST /ads/*/sync'],
    operation: 'CONFIGURE',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Khong dua token/raw secret vao prompt; chi dung trang thai/cau hinh can thiet.',
    writePolicy: 'Token/sync/config can xac nhan va audit; khong bao gio hien secret.',
    requiresConfirmation: true,
    requiresApproval: true,
    requiresAudit: true,
    riskLevel: 'CRITICAL',
  },
  {
    key: 'messages_and_conversations',
    group: 'Messaging',
    userIntent: 'Doc hoi thoai, takeover/release, gui tin, tao lead/order tu hoi thoai.',
    allowedAssistantTypes: [DIRECTOR, OPS, SALE, ADS, LEAD_CARE, PARENT],
    allowedRoles: [Role.DIRECTOR, Role.OPS, Role.SALE, Role.ADSMANAGER, Role.PARENT],
    apiRoutes: ['GET /chatbot/conversations', 'GET /chatbot/conversations/:id/messages', 'POST /chatbot/conversations/:id/messages', 'POST /chatbot/conversations/:id/takeover', 'POST /chatbot/conversations/:id/create-lead', 'POST /chatbot/conversations/:id/create-order', 'GET /messages/*'],
    operation: 'WORKFLOW_ACTION',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Chi nap conversation dang xu ly va messages gan nhat; khong nap toan bo inbox.',
    writePolicy: 'Gui tin hoac tao lead/order can preview noi dung/payload va xac nhan.',
    requiresConfirmation: true,
    requiresApproval: false,
    requiresAudit: true,
    riskLevel: 'HIGH',
  },
  {
    key: 'materials_quizzes_learning_content',
    group: 'Learning content',
    userIntent: 'Tim hoc lieu, tao/sua hoc lieu, quiz, cham diem quiz.',
    allowedAssistantTypes: [DIRECTOR, OPS, TEACHER, EXPERIENCE_TEACHER, PARENT, STUDENT],
    allowedRoles: [Role.DIRECTOR, Role.OPS, Role.TEACHER, Role.EXPERIENCE_TEACHER, Role.PARENT, Role.STUDENT],
    apiRoutes: ['GET /teaching-materials', 'POST /teaching-materials', 'PATCH /teaching-materials/:id', 'GET /quizzes', 'POST /quizzes', 'POST /quizzes/:id/attempts', 'PATCH /quizzes/attempts/:attemptId/grade'],
    operation: 'WORKFLOW_ACTION',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Student/parent chi noi dung duoc phep xem; create/update chi role manage.',
    writePolicy: 'AI co the tao nhap, nhung publication/cham diem can xac nhan.',
    requiresConfirmation: true,
    requiresApproval: false,
    requiresAudit: true,
    riskLevel: 'MEDIUM',
  },
  {
    key: 'notifications_and_exports',
    group: 'Communications and exports',
    userIntent: 'Gui thong bao, xem thong bao, export bao cao.',
    allowedAssistantTypes: [DIRECTOR, ACCOUNTING, OPS, SALE, PARENT, TEACHER, SHAREHOLDER],
    allowedRoles: [Role.DIRECTOR, Role.ACCOUNTING, Role.OPS, Role.SALE, Role.PARENT, Role.TEACHER, Role.SHAREHOLDER],
    apiRoutes: ['GET /notifications', 'POST /notifications/bulk-preview', 'POST /notifications/bulk-send', 'GET /export/*'],
    operation: 'EXPORT',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Export va bulk notification can filter/preview; khong dua file lon vao prompt.',
    writePolicy: 'Gui bulk notification can preview nguoi nhan + noi dung + confirm.',
    requiresConfirmation: true,
    requiresApproval: true,
    requiresAudit: true,
    riskLevel: 'HIGH',
  },
  {
    key: 'ai_api_and_chatbot_management',
    group: 'AI administration',
    userIntent: 'Quan ly OpenAI token, fanpage, AI assistant profile, rules prompt.',
    allowedAssistantTypes: [DIRECTOR],
    allowedRoles: [Role.DIRECTOR],
    apiRoutes: ['GET /chatbot/openai-tokens', 'POST /chatbot/openai-tokens', 'PATCH /chatbot/openai-tokens/:id', 'GET /chatbot/ai-assistant-profiles', 'POST /chatbot/ai-assistant-profiles', 'PATCH /chatbot/ai-assistant-profiles/:id'],
    operation: 'CONFIGURE',
    dataScope: 'GLOBAL',
    contextPolicy: 'Khong dua decrypted token vao prompt; chi hien metadata token/profile.',
    writePolicy: 'Tao/sua/xoa token/profile can confirm, audit va chi DIRECTOR.',
    requiresConfirmation: true,
    requiresApproval: true,
    requiresAudit: true,
    riskLevel: 'CRITICAL',
  },
  {
    key: 'audit_users_security',
    group: 'Security and governance',
    userIntent: 'Tra audit, quan ly user, phan quyen, khoa/mo tai khoan.',
    allowedAssistantTypes: [DIRECTOR],
    allowedRoles: [Role.DIRECTOR],
    apiRoutes: ['GET /audit-log', 'GET /audit-log/stats', 'GET /users', 'POST /users', 'PATCH /users/:id', 'DELETE /users/:id'],
    operation: 'CONFIGURE',
    dataScope: 'GLOBAL',
    contextPolicy: 'Audit detail phai co filter; khong nap toan bo log.',
    writePolicy: 'Quan tri user/quyen la critical, can confirm va audit.',
    requiresConfirmation: true,
    requiresApproval: true,
    requiresAudit: true,
    riskLevel: 'CRITICAL',
  },
  {
    key: 'loans_suppliers_expenses',
    group: 'Finance operations',
    userIntent: 'Khoan vay, nha cung cap, bao gia, thanh toan NCC, chi phi.',
    allowedAssistantTypes: [DIRECTOR, ACCOUNTING, OPS, SHAREHOLDER],
    allowedRoles: [Role.DIRECTOR, Role.ACCOUNTING, Role.OPS, Role.SHAREHOLDER],
    apiRoutes: ['GET /loans', 'POST /loans/*', 'GET /supplier-quotes', 'POST /supplier-quotes/*', 'GET /supplier-payments', 'POST /supplier-payments/*', 'GET /expenses', 'POST /expenses/*'],
    operation: 'WORKFLOW_ACTION',
    dataScope: 'ROLE_SCOPE',
    contextPolicy: 'Shareholder chi aggregate/report; accounting/director co the xem chi tiet co filter.',
    writePolicy: 'Tao/duyet thanh toan/vay/chi phi can confirm va audit.',
    requiresConfirmation: true,
    requiresApproval: true,
    requiresAudit: true,
    riskLevel: 'CRITICAL',
  },
  {
    key: 'system_guidance',
    group: 'System guidance',
    userIntent: 'Hoi cach dung he thong, man hinh nao, quy trinh thao tac.',
    allowedAssistantTypes: [DIRECTOR, ACCOUNTING, OPS, TEACHER, EXPERIENCE_TEACHER, PARENT, STUDENT, SALE, ADS, SHAREHOLDER, INTERNAL, LEAD_CARE],
    allowedRoles: [Role.DIRECTOR, Role.ACCOUNTING, Role.OPS, Role.TEACHER, Role.EXPERIENCE_TEACHER, Role.PARENT, Role.STUDENT, Role.SALE, Role.ADSMANAGER, Role.SHAREHOLDER],
    apiRoutes: ['STATIC guide context'],
    operation: 'READ_SUMMARY',
    dataScope: 'NO_DATABASE',
    contextPolicy: 'Uu tien tra loi tu guide/static docs, khong doc DB neu chi hoi cach dung.',
    writePolicy: 'Khong co thao tac ghi.',
    requiresConfirmation: false,
    requiresApproval: false,
    requiresAudit: false,
    riskLevel: 'LOW',
  },
];

export function getAssistantPermissionProfile(assistantType: AiAssistantType) {
  return AI_ASSISTANT_PERMISSION_CATALOG[assistantType];
}

export function getAllowedSituationsForAssistant(assistantType: AiAssistantType) {
  return AI_ERP_SITUATION_CATALOG.filter((item) => item.allowedAssistantTypes.includes(assistantType));
}
