import { Role } from '../common/interfaces/role.enum';
import { DirectorAiContextMode } from './dto/director-ai-chat.dto';

export type DirectorAiToolKey =
  | 'daily_tasks'
  | 'pending_approvals_summary'
  | 'director_dashboard'
  | 'accounting_dashboard'
  | 'ops_dashboard'
  | 'financial_overview'
  | 'financial_alerts'
  | 'profit_and_loss'
  | 'revenue_report'
  | 'sales_dashboard'
  | 'aging_report'
  | 'cash_flow'
  | 'ads_actions_required'
  | 'audit_stats'
  | 'teacher_kpi'
  | 'employee_performance'
  | 'retention'
  | 'forecast'
  | 'director_guide';

export type DirectorAiRiskLevel = 'LOW' | 'MEDIUM' | 'HIGH';
export type DirectorAiToolOperation = 'READ' | 'WRITE_PROPOSAL';

export interface DirectorAiToolCatalogItem {
  key: DirectorAiToolKey;
  label: string;
  description: string;
  businessName: string;
  businessMeaning: string;
  endpoint: string;
  serviceMethod: string;
  method: 'GET' | 'POST' | 'PATCH' | 'DELETE' | 'STATIC';
  inputSchemaSummary: string;
  outputSchemaSummary: string;
  allowedRoles: readonly Role[];
  dataScope: string;
  dataPolicy: string;
  defaultDateRange: 'none' | 'current_month' | 'service_default' | 'static';
  maxLimit?: number;
  cacheTtlSeconds: number;
  riskLevel: DirectorAiRiskLevel;
  operation: DirectorAiToolOperation;
  requiresConfirmation: boolean;
  requiresApproval: boolean;
  auditRequired: boolean;
  triggerKeywords: readonly string[];
  exampleUserQuestions: readonly string[];
  responseGuidance: string;
  failureCases: readonly string[];
  enabled: boolean;
}

const DIRECTOR_ONLY = [Role.DIRECTOR] as const;

export const DIRECTOR_AI_TOOL_CATALOG = {
  daily_tasks: {
    key: 'daily_tasks',
    label: 'Viec trong ngay',
    description: 'Lay hang doi viec can xu ly theo role DIRECTOR.',
    businessName: 'Bang viec hang ngay cua giam doc',
    businessMeaning: 'Cho biet cac viec uu tien, deadline va diem can can thiep trong ngay.',
    endpoint: 'GET /dashboard/daily-tasks?role=DIRECTOR',
    serviceMethod: 'DashboardService.getDailyTasks(Role.DIRECTOR, userId)',
    method: 'GET',
    inputSchemaSummary: 'userId tu JWT, role DIRECTOR.',
    outputSchemaSummary: 'Nhom viec can lam, viec qua han, viec can phe duyet va lien ket man hinh xu ly.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Theo quyen va user dang dang nhap.',
    dataPolicy: 'Summary va toi da cac item da duoc service gioi han.',
    defaultDateRange: 'service_default',
    maxLimit: 30,
    cacheTtlSeconds: 60,
    riskLevel: 'LOW',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['hom nay', 'viec trong ngay', 'can xu ly', 'can lam gi', 'uu tien', 'deadline', 'qua han'],
    exampleUserQuestions: ['Hom nay can xu ly gi?', 'Viec nao dang qua han?'],
    responseGuidance: 'Tra loi theo thu tu uu tien, neu co viec can phe duyet thi neu ro man hinh can vao.',
    failureCases: ['Khong co task nao duoc tra ve', 'Role khong hop le'],
    enabled: true,
  },
  pending_approvals_summary: {
    key: 'pending_approvals_summary',
    label: 'Tom tat hang cho duyet',
    description: 'Lay so dem payroll, invoice, top-up, giao vien, lop va session change dang cho duyet.',
    businessName: 'Hang cho phe duyet',
    businessMeaning: 'Giup giam doc thay cac nghiep vu dang cho quyet dinh de tranh tre SLA.',
    endpoint: 'GET /pending-approvals/summary',
    serviceMethod: 'PendingApprovalsService.getSummary()',
    method: 'GET',
    inputSchemaSummary: 'Khong can tham so.',
    outputSchemaSummary: 'So luong tung loai phe duyet va tong backlog.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Toan he thong, chi so dem tong hop.',
    dataPolicy: 'Chi lay summary count, khong mo danh sach chi tiet neu nguoi dung chua hoi.',
    defaultDateRange: 'none',
    cacheTtlSeconds: 45,
    riskLevel: 'LOW',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['cho duyet', 'phe duyet', 'duyet', 'approval', 'invoice', 'hoa don', 'top up', 'topup', 'payroll', 'luong'],
    exampleUserQuestions: ['Con gi cho toi duyet?', 'Loai phe duyet nao dang bi ton?'],
    responseGuidance: 'Chi neu so tong hop; neu can xu ly tung ban ghi, yeu cau nguoi dung mo man hinh phe duyet hoac xac nhan drill-down.',
    failureCases: ['Service tra ve rong', 'Khong co queue cho duyet'],
    enabled: true,
  },
  director_dashboard: {
    key: 'director_dashboard',
    label: 'Dashboard giam doc',
    description: 'Tong quan doanh thu, loi nhuan, session, nguoi dung, ticket va activity gan day.',
    businessName: 'Tong quan dieu hanh',
    businessMeaning: 'Tam nhin nhanh ve suc khoe doanh nghiep trong khoang ngay dang xet.',
    endpoint: 'GET /dashboard/director',
    serviceMethod: 'DashboardService.getDirectorDashboard(fromDate, toDate)',
    method: 'GET',
    inputSchemaSummary: 'fromDate, toDate; mac dinh thang hien tai neu nguoi dung khong chon.',
    outputSchemaSummary: 'Doanh thu, chi phi giao vien, loi nhuan, session, payroll, ticket, wallet va activity gan day.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Aggregate toan he thong theo khoang ngay.',
    dataPolicy: 'Aggregate theo khoang ngay mac dinh thang hien tai, recent list da limit trong service.',
    defaultDateRange: 'current_month',
    maxLimit: 10,
    cacheTtlSeconds: 120,
    riskLevel: 'LOW',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['tong quan', 'dashboard', 'suc khoe', 'he thong', 'doanh nghiep', 'tinh hinh'],
    exampleUserQuestions: ['Tong quan thang nay the nao?', 'Diem nao dang xau nhat tren dashboard?'],
    responseGuidance: 'Mo dau bang ket luan, sau do neu 3-5 chi so chinh va canh bao.',
    failureCases: ['Khoang ngay khong hop le', 'Thieu du lieu giao dich'],
    enabled: true,
  },
  accounting_dashboard: {
    key: 'accounting_dashboard',
    label: 'Tai chinh ke toan',
    description: 'Vi, giao dich, payroll, doanh thu va top-up dang cho xu ly.',
    businessName: 'Dashboard ke toan',
    businessMeaning: 'Theo doi tien, vi, giao dich, payroll va top-up de phong rui ro dong tien.',
    endpoint: 'GET /dashboard/accounting',
    serviceMethod: 'DashboardService.getAccountingDashboard(fromDate, toDate)',
    method: 'GET',
    inputSchemaSummary: 'fromDate, toDate; mac dinh thang hien tai.',
    outputSchemaSummary: 'Financial summary, wallet aggregate, pending top-up, payroll aggregate, ledger gan day, revenue.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Aggregate tai chinh va danh sach gan day da gioi han.',
    dataPolicy: 'Aggregate va danh sach gan day co limit san trong service.',
    defaultDateRange: 'current_month',
    maxLimit: 20,
    cacheTtlSeconds: 120,
    riskLevel: 'MEDIUM',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['ke toan', 'tai chinh', 'giao dich', 'vi', 'wallet', 'top up', 'topup', 'payroll', 'luong'],
    exampleUserQuestions: ['Dong tien ke toan co bat thuong khong?', 'Top-up nao dang ton?'],
    responseGuidance: 'Neu co tien va queue cho duyet, tach ro so lieu da thu, dang cho xu ly va rui ro.',
    failureCases: ['Du lieu ledger chua dong bo', 'Khoang ngay qua rong'],
    enabled: true,
  },
  ops_dashboard: {
    key: 'ops_dashboard',
    label: 'Van hanh',
    description: 'Lop, buoi hoc, giao vien, hoc sinh, ticket va backlog van hanh.',
    businessName: 'Dashboard van hanh',
    businessMeaning: 'Phat hien diem nghen lop hoc, buoi hoc, ticket va nguon luc giao vien.',
    endpoint: 'GET /dashboard/ops',
    serviceMethod: 'DashboardService.getOpsDashboard(userId)',
    method: 'GET',
    inputSchemaSummary: 'userId tu JWT de dem viec gan cho nguoi dung, cac aggregate con lai toan he thong.',
    outputSchemaSummary: 'So lop, session, giao vien, hoc sinh, ticket qua han va ticket gan day.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Van hanh toan he thong va mot phan theo user.',
    dataPolicy: 'Aggregate va recent tickets co limit.',
    defaultDateRange: 'service_default',
    maxLimit: 15,
    cacheTtlSeconds: 120,
    riskLevel: 'LOW',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['van hanh', 'ops', 'lop', 'buoi hoc', 'session', 'ticket', 'finalize', 'giao vien tre', 'hoc sinh pending'],
    exampleUserQuestions: ['Van hanh co diem nghen nao?', 'Session nao can finalize?'],
    responseGuidance: 'Neu co ticket qua han hoac session can finalize, dua len dau danh sach.',
    failureCases: ['opsUserId khong hop le', 'Ticket/session chua du trang thai'],
    enabled: true,
  },
  financial_overview: {
    key: 'financial_overview',
    label: 'Tong quan tai chinh',
    description: 'Tong quan dong tien va cac chi so tai chinh dieu hanh.',
    businessName: 'Financial Control overview',
    businessMeaning: 'Kiem tra suc khoe tai chinh cap dieu hanh theo P&L, cong no, cash va canh bao.',
    endpoint: 'GET /financial-control/overview',
    serviceMethod: 'FinancialControlService.getFinancialOverview(fromDate, toDate)',
    method: 'GET',
    inputSchemaSummary: 'startDate/fromDate, endDate/toDate; mac dinh thang hien tai.',
    outputSchemaSummary: 'Tong hop doanh thu, chi phi, loi nhuan, cash va cac chi so lien quan.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Aggregate tai chinh toan he thong.',
    dataPolicy: 'Chi lay output tong hop tu Financial Control.',
    defaultDateRange: 'current_month',
    cacheTtlSeconds: 120,
    riskLevel: 'MEDIUM',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['tai chinh', 'financial control', 'tong quan tai chinh', 'suc khoe tai chinh', 'loi nhuan', 'chi phi'],
    exampleUserQuestions: ['Tai chinh thang nay co on khong?', 'Chi so nao can can thiep?'],
    responseGuidance: 'Phan tach ket qua, bien dong, rui ro va viec can xu ly.',
    failureCases: ['Nguon du lieu tai chinh chua dong bo', 'Khoang ngay khong co du lieu'],
    enabled: true,
  },
  financial_alerts: {
    key: 'financial_alerts',
    label: 'Canh bao tai chinh',
    description: 'Lay danh sach canh bao/rui ro tai chinh dang mo.',
    businessName: 'Canh bao tai chinh',
    businessMeaning: 'Phat hien loi nhuan am, cong no, dong tien, giao dich va nguong canh bao.',
    endpoint: 'GET /financial-control/alerts',
    serviceMethod: 'FinancialControlService.getFinancialAlerts()',
    method: 'GET',
    inputSchemaSummary: 'Khong can tham so.',
    outputSchemaSummary: 'Danh sach alert va muc do uu tien/rui ro.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Canh bao da tinh san toan he thong.',
    dataPolicy: 'Chi lay alert da tinh san, khong quet collection tho.',
    defaultDateRange: 'service_default',
    cacheTtlSeconds: 60,
    riskLevel: 'MEDIUM',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['canh bao', 'rui ro', 'bat thuong', 'am tien', 'lo', 'qua han', 'bao dong'],
    exampleUserQuestions: ['Rui ro tai chinh nao can xu ly ngay?', 'Canh bao nao nghiem trong nhat?'],
    responseGuidance: 'Sap xep theo muc do nghiem trong, neu ro bang chung va hanh dong de xuat.',
    failureCases: ['Khong co alert', 'Alert service loi'],
    enabled: true,
  },
  profit_and_loss: {
    key: 'profit_and_loss',
    label: 'P&L',
    description: 'Bao cao lai lo theo khoang ngay.',
    businessName: 'Bao cao lai lo',
    businessMeaning: 'Cho biet doanh thu, chi phi, lai gop va lai rong de ra quyet dinh tai chinh.',
    endpoint: 'GET /financial-control/profit-and-loss',
    serviceMethod: 'FinancialControlService.getProfitAndLoss(fromDate, toDate)',
    method: 'GET',
    inputSchemaSummary: 'startDate/fromDate, endDate/toDate, basis tuy chon.',
    outputSchemaSummary: 'Doanh thu, chi phi, loi nhuan theo nhom va tong hop P&L.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Aggregate P&L toan he thong theo khoang ngay.',
    dataPolicy: 'Aggregate P&L theo khoang ngay mac dinh thang hien tai.',
    defaultDateRange: 'current_month',
    cacheTtlSeconds: 120,
    riskLevel: 'MEDIUM',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['p&l', 'lai lo', 'loi nhuan', 'profit', 'loss', 'bien loi nhuan', 'margin'],
    exampleUserQuestions: ['P&L thang nay the nao?', 'Ly do loi nhuan giam la gi?'],
    responseGuidance: 'Khong ket luan nguyen nhan neu context khong co bang chung; neu can, de xuat goi them dashboard lien quan.',
    failureCases: ['Du lieu chi phi hoac doanh thu chua day du'],
    enabled: true,
  },
  revenue_report: {
    key: 'revenue_report',
    label: 'Bao cao doanh thu',
    description: 'Doanh thu theo thang/quy/nam va bien dong.',
    businessName: 'Bao cao doanh thu',
    businessMeaning: 'Theo doi tang truong doanh thu va xu huong theo ky.',
    endpoint: 'GET /dashboard/director/revenue',
    serviceMethod: 'DashboardService.getRevenueReport(period, fromDate, toDate)',
    method: 'GET',
    inputSchemaSummary: 'period monthly/quarterly/yearly; fromDate, toDate.',
    outputSchemaSummary: 'Series doanh thu theo ky, tong doanh thu va bien dong.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Aggregate doanh thu.',
    dataPolicy: 'Aggregate doanh thu, khong lay tung giao dich tho.',
    defaultDateRange: 'current_month',
    cacheTtlSeconds: 180,
    riskLevel: 'LOW',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['doanh thu', 'revenue', 'tang truong', 'sales revenue', 'so sanh doanh thu'],
    exampleUserQuestions: ['Doanh thu thang nay tang hay giam?', 'Ky nao doanh thu tot nhat?'],
    responseGuidance: 'Neu noi ve tang giam, neu ro moc so sanh co trong context.',
    failureCases: ['Khong co doanh thu trong khoang ngay'],
    enabled: true,
  },
  sales_dashboard: {
    key: 'sales_dashboard',
    label: 'Kinh doanh',
    description: 'Lead, order, pipeline va hieu suat sale theo khoang ngay.',
    businessName: 'Dashboard kinh doanh',
    businessMeaning: 'Theo doi pipeline lead/order, chuyen doi va hieu suat doanh thu cua doi kinh doanh.',
    endpoint: 'GET /dashboard/sales',
    serviceMethod: 'DashboardService.getSalesDashboard(undefined, fromDate, toDate)',
    method: 'GET',
    inputSchemaSummary: 'saleId optional; chatbot giam doc de trong saleId de xem toan bo, fromDate, toDate.',
    outputSchemaSummary: 'Pipeline, doanh thu, lead/order va cac chi so sale tong hop.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Toan bo sales dashboard theo khoang ngay.',
    dataPolicy: 'Aggregate theo khoang ngay, khong lay raw lead/order neu chua xac nhan drill-down.',
    defaultDateRange: 'current_month',
    cacheTtlSeconds: 120,
    riskLevel: 'LOW',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['sale', 'sales', 'kinh doanh', 'lead', 'order', 'pipeline', 'chuyen doi', 'conversion'],
    exampleUserQuestions: ['Sales co diem nghen nao?', 'Pipeline thang nay ra sao?'],
    responseGuidance: 'Neu du lieu co pipeline, neu ro nut that lead -> order -> invoice; tranh goi ten ca nhan neu khong can.',
    failureCases: ['Du lieu sale dashboard rong', 'Khoang ngay khong co lead/order'],
    enabled: true,
  },
  aging_report: {
    key: 'aging_report',
    label: 'Cong no',
    description: 'Bao cao tuoi no va cac khoan can thu/tra qua han.',
    businessName: 'Aging report',
    businessMeaning: 'Xac dinh cong no qua han, khoan thu/tra can uu tien va rui ro thu tien.',
    endpoint: 'GET /financial-control/aging-report',
    serviceMethod: 'FinancialControlService.getAgingReport(user)',
    method: 'GET',
    inputSchemaSummary: 'JWT user de ap dung quyen.',
    outputSchemaSummary: 'Bucket tuoi no, tong tien va danh sach da duoc service gioi han.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Cong no theo pham vi quyen DIRECTOR.',
    dataPolicy: 'Dua tren aggregate aging; khong quet tung invoice/order neu chua can.',
    defaultDateRange: 'service_default',
    cacheTtlSeconds: 120,
    riskLevel: 'MEDIUM',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['cong no', 'aging', 'qua han', 'no xau', 'phai thu', 'phai tra', 'thu tien'],
    exampleUserQuestions: ['Cong no nao qua han nhieu nhat?', 'Can thu tien o nhom nao truoc?'],
    responseGuidance: 'Phan loai theo tuoi no va uu tien xu ly; khong de xuat xoa/noi bo cong no.',
    failureCases: ['Aging service chua co du lieu', 'Du lieu invoice/order thieu ngay han'],
    enabled: true,
  },
  cash_flow: {
    key: 'cash_flow',
    label: 'Dong tien',
    description: 'Bao cao dong tien theo ngay/tuan/thang.',
    businessName: 'Cash flow',
    businessMeaning: 'Theo doi tien vao, tien ra va thoi diem co nguy co thieu tien.',
    endpoint: 'GET /financial-control/cash-flow',
    serviceMethod: 'FinancialControlService.getCashFlow({ startDate, endDate, groupBy, basis })',
    method: 'GET',
    inputSchemaSummary: 'startDate, endDate, groupBy day/week/month, basis cash/accrual.',
    outputSchemaSummary: 'Dong tien theo ky, tong tien vao/ra va so du tham chieu.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Aggregate dong tien theo khoang ngay.',
    dataPolicy: 'Group by week mac dinh trong chatbot de tranh context qua lon.',
    defaultDateRange: 'current_month',
    cacheTtlSeconds: 120,
    riskLevel: 'MEDIUM',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['dong tien', 'cash flow', 'cashflow', 'tien vao', 'tien ra', 'thieu tien', 'du tien'],
    exampleUserQuestions: ['Dong tien tu nay den cuoi thang co on khong?', 'Tuan nao tien ra lon nhat?'],
    responseGuidance: 'Neu co am dong tien, neu moc thoi gian va goi them financial_alerts neu can.',
    failureCases: ['Khoang ngay qua ngan hoac khong co giao dich'],
    enabled: true,
  },
  ads_actions_required: {
    key: 'ads_actions_required',
    label: 'Quang cao can xu ly',
    description: 'Khuyen nghi hanh dong voi chien dich/ad group theo loi nhuan va hieu qua.',
    businessName: 'Ads actions required',
    businessMeaning: 'Phat hien chien dich can tang/giam ngan sach, dung, hoac can theo doi them.',
    endpoint: 'GET /ads/actions-required',
    serviceMethod: 'AdsAnalyticsService.getActionsRequired()',
    method: 'GET',
    inputSchemaSummary: 'Options optional; chatbot dung default cua service.',
    outputSchemaSummary: 'Danh sach action suggestions va summary hieu qua quang cao.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Tong hop quang cao theo default lookback cua service.',
    dataPolicy: 'Chi lay de xuat da tinh san; moi thay doi ngan sach phai qua xac nhan rieng.',
    defaultDateRange: 'service_default',
    cacheTtlSeconds: 180,
    riskLevel: 'MEDIUM',
    operation: 'READ',
    requiresConfirmation: true,
    requiresApproval: true,
    auditRequired: true,
    triggerKeywords: ['ads', 'quang cao', 'marketing', 'facebook ads', 'google ads', 'ngan sach', 'campaign', 'ad group'],
    exampleUserQuestions: ['Quang cao nao can can thiep?', 'Co nen tang ngan sach campaign nao?'],
    responseGuidance: 'Chi de xuat hanh dong; khong khang dinh da doi ngan sach neu chua co API ghi va xac nhan.',
    failureCases: ['Ads data chua dong bo', 'Khong co action suggestion'],
    enabled: true,
  },
  audit_stats: {
    key: 'audit_stats',
    label: 'Audit he thong',
    description: 'Thong ke audit log hom nay va 7 ngay gan nhat.',
    businessName: 'Audit log stats',
    businessMeaning: 'Giam sat ky luat van hanh, muc do thao tac va diem bat thuong theo module/action.',
    endpoint: 'GET /audit-log/stats',
    serviceMethod: 'AuditLogService.getStats()',
    method: 'GET',
    inputSchemaSummary: 'Khong can tham so.',
    outputSchemaSummary: 'So audit hom nay, 7 ngay, theo module, theo action va chuoi activity.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Thong ke audit toan he thong trong ngay va 7 ngay.',
    dataPolicy: 'Chi lay stats, khong lay noi dung log chi tiet neu nguoi dung chua hoi.',
    defaultDateRange: 'service_default',
    cacheTtlSeconds: 120,
    riskLevel: 'LOW',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['audit', 'nhat ky', 'lich su thao tac', 'ai lam', 'bat thuong he thong', 'log'],
    exampleUserQuestions: ['Hom nay ai thao tac nhieu bat thuong?', 'Module nao co nhieu thay doi?'],
    responseGuidance: 'Tra loi bang xu huong tong hop; neu can truy vet ca nhan, yeu cau xac nhan goi audit log chi tiet trong tuong lai.',
    failureCases: ['Audit log rong', 'Thong ke audit loi'],
    enabled: true,
  },
  teacher_kpi: {
    key: 'teacher_kpi',
    label: 'KPI giao vien',
    description: 'Hieu suat va chat luong giao vien.',
    businessName: 'Teacher KPI',
    businessMeaning: 'Danh gia chat luong day, hoan thanh buoi hoc va rui ro nguon luc giao vien.',
    endpoint: 'GET /dashboard/director/teacher-kpi',
    serviceMethod: 'DashboardService.getTeacherKPI(fromDate, toDate)',
    method: 'GET',
    inputSchemaSummary: 'fromDate, toDate.',
    outputSchemaSummary: 'Chi so KPI giao vien theo khoang ngay.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Aggregate giao vien.',
    dataPolicy: 'Aggregate theo khoang ngay, cat gon cac bang dai.',
    defaultDateRange: 'current_month',
    cacheTtlSeconds: 180,
    riskLevel: 'LOW',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['kpi giao vien', 'teacher kpi', 'chat luong giao vien', 'giao vien', 'day tre', 'no show'],
    exampleUserQuestions: ['Giao vien nao can theo doi?', 'KPI giao vien thang nay the nao?'],
    responseGuidance: 'Neu co xep hang ca nhan, dua ra canh bao can kiem tra them truoc khi ket luan nhan su.',
    failureCases: ['Khong co session trong khoang ngay'],
    enabled: true,
  },
  employee_performance: {
    key: 'employee_performance',
    label: 'Hieu suat nhan su',
    description: 'So sanh hieu suat Sales, OPS va nhan su lien quan.',
    businessName: 'Employee performance',
    businessMeaning: 'Theo doi hieu suat nhan su van hanh/kinh doanh va diem can coaching.',
    endpoint: 'GET /dashboard/director/employee-performance',
    serviceMethod: 'DashboardService.getEmployeePerformance()',
    method: 'GET',
    inputSchemaSummary: 'Khong can tham so.',
    outputSchemaSummary: 'Hieu suat nhan su da tinh san theo module.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Aggregate nhan su.',
    dataPolicy: 'Lay dashboard hieu suat da tinh san.',
    defaultDateRange: 'service_default',
    cacheTtlSeconds: 180,
    riskLevel: 'LOW',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['nhan su', 'employee', 'hieu suat', 'performance', 'kpi nhan su', 'sales ops'],
    exampleUserQuestions: ['Nhan su nao dang kem hieu suat?', 'Can coaching bo phan nao?'],
    responseGuidance: 'Neu so lieu lien quan ca nhan, trinh bay nhu dau hieu can xem lai, khong ket luan ky luat.',
    failureCases: ['Du lieu KPI nhan su rong'],
    enabled: true,
  },
  retention: {
    key: 'retention',
    label: 'Duy tri hoc vien',
    description: 'Chi so retention va nguy co roi bo.',
    businessName: 'Retention metrics',
    businessMeaning: 'Theo doi kha nang duy tri hoc vien, churn va diem can cham soc.',
    endpoint: 'GET /dashboard/director/retention',
    serviceMethod: 'DashboardService.getRetentionMetrics()',
    method: 'GET',
    inputSchemaSummary: 'Khong can tham so.',
    outputSchemaSummary: 'Metric duy tri, roi bo, cohort hoac nhom rui ro neu co.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Aggregate retention.',
    dataPolicy: 'Aggregate retention.',
    defaultDateRange: 'service_default',
    cacheTtlSeconds: 180,
    riskLevel: 'LOW',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['duy tri', 'retention', 'roi bo', 'churn', 'ngung hoc', 'hoc vien roi'],
    exampleUserQuestions: ['Retention co giam khong?', 'Nhom nao de roi bo nhat?'],
    responseGuidance: 'Lien ket retention voi sales/ops neu context co du lieu; neu khong thi de xuat goi them ops_dashboard.',
    failureCases: ['Retention service khong co du lieu'],
    enabled: true,
  },
  forecast: {
    key: 'forecast',
    label: 'Du bao doanh thu',
    description: 'Du bao doanh thu theo du lieu hien co.',
    businessName: 'Revenue forecast',
    businessMeaning: 'Du bao doanh thu tu xu huong hien co de lap ke hoach.',
    endpoint: 'GET /dashboard/director/forecast',
    serviceMethod: 'DashboardService.getRevenueForecast()',
    method: 'GET',
    inputSchemaSummary: 'Khong can tham so.',
    outputSchemaSummary: 'Du bao doanh thu va gia dinh tinh toan neu service cung cap.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Forecast aggregate.',
    dataPolicy: 'Lay output forecast da tinh san.',
    defaultDateRange: 'service_default',
    cacheTtlSeconds: 300,
    riskLevel: 'LOW',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: true,
    triggerKeywords: ['du bao', 'forecast', 'du kien', 'thang sau', 'quy sau', 'muc tieu doanh thu'],
    exampleUserQuestions: ['Du bao doanh thu thang sau?', 'Co dat muc tieu thang nay khong?'],
    responseGuidance: 'Nhac ro day la du bao; neu thieu gia dinh, khong bien du bao thanh cam ket.',
    failureCases: ['Khong du du lieu de forecast'],
    enabled: true,
  },
  director_guide: {
    key: 'director_guide',
    label: 'Huong dan he thong',
    description: 'So tay ngan gon cho role DIRECTOR va cac man hinh can dung.',
    businessName: 'Huong dan dieu hanh ERP',
    businessMeaning: 'Giup giam doc biet vao man hinh nao, doc so lieu nao va quy trinh nao can tuan thu.',
    endpoint: 'STATIC director-ai guide context',
    serviceMethod: 'DirectorAiService.getDirectorGuideContext()',
    method: 'STATIC',
    inputSchemaSummary: 'Khong truy cap database.',
    outputSchemaSummary: 'Routine, key screens, quy tac cam va quy trinh su dung.',
    allowedRoles: DIRECTOR_ONLY,
    dataScope: 'Noi dung tinh trong backend.',
    dataPolicy: 'Noi dung tinh, khong truy cap database.',
    defaultDateRange: 'static',
    cacheTtlSeconds: 3600,
    riskLevel: 'LOW',
    operation: 'READ',
    requiresConfirmation: false,
    requiresApproval: false,
    auditRequired: false,
    triggerKeywords: ['huong dan', 'cach dung', 'vao dau', 'man hinh', 'quy trinh', 'sop', 'su dung he thong'],
    exampleUserQuestions: ['Toi muon xem cong no thi vao dau?', 'Quy trinh xu ly dau ngay la gi?'],
    responseGuidance: 'Tra loi bang thao tac ngan gon va man hinh can vao; khong doc database.',
    failureCases: ['Noi dung guide thieu module moi'],
    enabled: true,
  },
} as const satisfies Record<DirectorAiToolKey, DirectorAiToolCatalogItem>;

export const DIRECTOR_AI_MODE_TOOL_KEYS = {
  [DirectorAiContextMode.AUTO]: [],
  [DirectorAiContextMode.OVERVIEW]: ['director_dashboard', 'pending_approvals_summary', 'financial_alerts', 'audit_stats'],
  [DirectorAiContextMode.FINANCE]: [
    'accounting_dashboard',
    'financial_overview',
    'financial_alerts',
    'profit_and_loss',
    'cash_flow',
    'aging_report',
  ],
  [DirectorAiContextMode.OPERATIONS]: ['ops_dashboard', 'director_dashboard', 'pending_approvals_summary'],
  [DirectorAiContextMode.SALES]: ['sales_dashboard', 'revenue_report', 'retention', 'forecast', 'ads_actions_required'],
  [DirectorAiContextMode.HR]: ['employee_performance', 'teacher_kpi', 'ops_dashboard'],
  [DirectorAiContextMode.GUIDE]: ['director_guide'],
} as const satisfies Record<DirectorAiContextMode, readonly DirectorAiToolKey[]>;

export function getEnabledDirectorAiToolCatalog() {
  return Object.values(DIRECTOR_AI_TOOL_CATALOG).filter((item) => item.enabled);
}

export function getDirectorAiToolCatalogItem(key: DirectorAiToolKey) {
  return DIRECTOR_AI_TOOL_CATALOG[key];
}
